/****** Object:  Table [dbo].[HR_CAPACITACIONFOLIOS]    Script Date: 7/01/2019 14:14:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HR_CAPACITACIONFOLIOS](
	[CAPACITACION] [varchar](20) NOT NULL,
	[COMPANYOWNER] [varchar](8) NOT NULL,
	[SECUENCIA] [int] NOT NULL,
	[ARCHIVO] [varchar](500) NULL,
	[ULTIMOUSUARIO] [varchar](25) NULL,
	[ULTIMAFECHAMODIF] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CAPACITACION] ASC,
	[COMPANYOWNER] ASC,
	[SECUENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


