export class PsConstante {
    static readonly APLICACION_CODIGO = 'PS';
    static readonly APLICACION_CODIGO_HR = 'HR';
    static readonly MISCELANEO_ESTADO = 'ESTADOBASI';
    static readonly MISCELANEO_DISCAPACIDAD = 'FLAGSINO';
    static readonly MISCELANEO_NIVEL_ACADEMICO = 'EMPNIVELAC';
    static readonly MISCELANEO_AREA_TRABAJO = 'AREATRAB';
    static readonly MISCELANEO_ESPECIALIDA_ACADEMICA_PROFESIONAL = 'NIVACAPROF';
    static readonly MISCELANEO_ESPECIALIDA_ACADEMICA_TECNICO = 'NIVACATECN';
    static readonly MISCELANEO_SEXO = 'SEXO';
    static readonly MISCELANEO_SUPLEMENTO_NUTRICIONAL = 'SUPLENUTRI';
    static readonly MISCELANEO_TIPO_DIETA_NINOS = 'TIPDIENIN';
    static readonly MISCELANEO_TIPO_DIETA_ADULTOS = 'TIPDIEADU';
    static readonly MISCELANEO_PERIMETRO_PIERNA = 'PERIPIERNA';
    static readonly MISCELANEO_PRESION_MANUAL = 'PRENMANU';
    static readonly MISCELANEO_HABIT_SOCIAL = 'HABISOCIAL';
    static readonly MISCELANEO_TRATAMIENTOS = 'RASTRATA';
    static readonly MISCELANEO_AYUDA_MEDICA = 'TIPAYUMEDI';
    static readonly MISCELANEO_VALOR_NUTRICIONAL_NINOS = 'NUTRVALNIN';
    static readonly MISCELANEO_VALOR_NUTRICIONAL_ADULTOS = 'NUTRVALADU';


    static readonly MISCELANEO_TABLA_SINO = 'FLAGSINO';
    static readonly MISCELANEO_HABILIDADES_OCUPACIONALES = 'HABIOCUPA';
    static readonly MISCELANEO_TIPO_INSTITUCION = 'TIPINSTCAP';
    static readonly MISCELANEO_NIVEL = 'NIVELCAPAC';
    static readonly MISCELANEO_GRADO_ACADEMICO_INICIAL = 'GRADOINIC';
    static readonly MISCELANEO_GRADO_ACADEMICO_PRIMARIA = 'GRADOPRIM';
    static readonly MISCELANEO_GRADO_ACADEMICO_SECUNDARIA = 'GRADOSECU';
    static readonly MISCELANEO_CAPACIDAD_PROMEDIO = 'CAPAPROME';
    static readonly MISCELANEO_TALLERES_PROMEDIO = 'TALLPROME';
    static readonly MISCELANEO_TIPO_COMUNICACION = 'TIPOCOMUN';
    static readonly MISCELANEO_TIPO_AYUDA_MEDICA = 'TIPAYUBIO';
    static readonly MISCELANEO_ESTADO_AYUDA_MEDICA = 'ESTAPAYUBI';
    static readonly MISCELANEO_ESTADOS_SALUD = 'ESTASALU';
    static readonly MISCELANEO_TERAPIAS = 'TERAPIA';
    static readonly MISCELANEO_CONDICION_SENSORIAL = 'SALCONDI';
    static readonly MISCELANEO_SUB_CONDICION_OFTA = 'SALSUBCOOF';
    static readonly MISCELANEO_SUB_CONDICION_AUDI = 'SALSUBCOAU';
    static readonly MISCELANEO_EXAMENES_AUXILIARES = 'EXAAUXI';
    static readonly MISCELANEO_ESTADOS_EXAMENES = 'EXARESU';
    static readonly MISCELANEO_DISCAPACIDADES = 'TIPDISCA';

    static readonly MISCELANEO_VALORACION_COGNITIVO = 'VMENCOG';
    static readonly MISCELANEO_VALORACION_AFECTIVO = 'VMENAFE';

    static readonly MISCELANEO_BARTHEL1 = 'BARTHEL1';
    static readonly MISCELANEO_BARTHEL2 = 'BARTHEL2';
    static readonly MISCELANEO_BARTHEL3 = 'BARTHEL3';
    static readonly MISCELANEO_BARTHEL4 = 'BARTHEL4';
    static readonly MISCELANEO_BARTHEL5 = 'BARTHEL5';
    static readonly MISCELANEO_BARTHEL6 = 'BARTHEL6';
    static readonly MISCELANEO_BARTHEL7 = 'BARTHEL7';
    static readonly MISCELANEO_BARTHEL8 = 'BARTHEL8';
    static readonly MISCELANEO_BARTHEL9 = 'BARTHEL9';
    static readonly MISCELANEO_BARTHEL10 = 'BARTHEL10';

    static readonly MISCELANEO_KATZ1 = 'KATZ1';
    static readonly MISCELANEO_KATZ2 = 'KATZ2';
    static readonly MISCELANEO_KATZ3 = 'KATZ3';
    static readonly MISCELANEO_KATZ4 = 'KATZ4';
    static readonly MISCELANEO_KATZ5 = 'KATZ5';
    static readonly MISCELANEO_KATZ6 = 'KATZ6';
    static readonly MISCELANEO_TIPO_PROGRAMA_ADULTOS = 'AAM';
    static readonly MISCELANEO_TIPO_EVALUACION_INICIAL = 'INI';
    static readonly MISCELANEO_TIPO_EVALUACION_PERIODICA = 'EVA';

    static readonly MISCELANEO_FACTOR_RH = 'FACTORRH';
    static readonly MISCELANEO_GRUPO_SANGUINEO = 'GRUPOSANGR';

}
