ALTER Procedure [sgseguridadsys].SNp_PS_ListarReporteGruposNutricionalesDB  
/*  
 Descripción: Store Procedure encargado de listar los valores para el reporte de   
     Grupos nutricionales que se aportan para una dieta balanceada según   
     condición  
 Input: @pFECHAINICIO Fecha de inicio del filtro  
   @pFECHAFIN Fecha fín del filtro  
   @pID_INSTITUCION código del instituto para el filtro  
   @pID_PROGRAMA código del Programa para el filtro  
 Output: Ninguno  
 Creado Por: José Alejandro Rojas Vallejos  
 Fecha Creación: 18/12/2018  
*/  
(  
 @pFECHAINICIO datetime,  
 @pFECHAFIN datetime,  
 @pID_INSTITUCION varchar(5),  
 @pID_PROGRAMA varchar(4)  
)  
As  
Begin  
	DECLARE @INSTITUCION VARCHAR(10) = @pID_INSTITUCION
	DECLARE @DESDE DATE = @pFECHAINICIO
	DECLARE @HASTA DATE = @pFECHAFIN

	SELECT 
	GENERAL.GRUPO, 
	GENERAL.INST, CAST(ROUND(CASE WHEN (GENERAL.INST+GENERAL.FUND+GENERAL.OTRO) = 0 THEN 0 ELSE GENERAL.INST*100/(GENERAL.INST+GENERAL.FUND+GENERAL.OTRO) END,2) AS decimal(5,2))POR_INST,
	GENERAL.FUND, CAST(ROUND(CASE WHEN (GENERAL.INST+GENERAL.FUND+GENERAL.OTRO) = 0 THEN 0 ELSE GENERAL.FUND*100/(GENERAL.INST+GENERAL.FUND+GENERAL.OTRO) END,2) AS decimal(5,2))POR_FUND,
	GENERAL.OTRO, CAST(ROUND(CASE WHEN (GENERAL.INST+GENERAL.FUND+GENERAL.OTRO) = 0 THEN 0 ELSE GENERAL.OTRO*100/(GENERAL.INST+GENERAL.FUND+GENERAL.OTRO) END,2) AS decimal(5,2)) POR_OTRO
	FROM (
	select
	A.DescripcionLocal GRUPO,
	ISNULL((SELECT SUM(X.CANTIDAD_SOLICITADA * Z.coeficiente)	FROM sgseguridadsys.PS_CONSUMO W JOIN sgseguridadsys.PS_CONSUMO_NUTRICIONAL X ON W.ID_INSTITUCION = X.ID_INSTITUCION AND W.ID_CONSUMO = X.ID_CONSUMO JOIN sgseguridadsys.PS_ITEM Y ON X.ID_ITEM = Y.ID_ITEM JOIN UnidadesMast Z ON Y.ID_UNIDAD_MEDIDA = Z.UnidadCodigo WHERE Y.ID_CLASE = A.CodigoElemento AND X.ID_INSTITUCION = @INSTITUCION AND W.FECHA_INICIO BETWEEN @DESDE AND @HASTA AND W.FECHA_FIN BETWEEN @DESDE AND @HASTA),0) AS INST,
	ISNULL((SELECT SUM(X.CANTIDAD_FUNDACION * Z.coeficiente)	FROM sgseguridadsys.PS_CONSUMO W JOIN sgseguridadsys.PS_CONSUMO_NUTRICIONAL X ON W.ID_INSTITUCION = X.ID_INSTITUCION AND W.ID_CONSUMO = X.ID_CONSUMO JOIN sgseguridadsys.PS_ITEM Y ON X.ID_ITEM = Y.ID_ITEM JOIN UnidadesMast Z ON Y.ID_UNIDAD_MEDIDA = Z.UnidadCodigo WHERE Y.ID_CLASE = A.CodigoElemento AND X.ID_INSTITUCION = @INSTITUCION AND W.FECHA_INICIO BETWEEN @DESDE AND @HASTA AND W.FECHA_FIN BETWEEN @DESDE AND @HASTA),0) AS FUND,
	ISNULL((SELECT SUM(X.CANTIDAD_OTROS * Z.coeficiente)		FROM sgseguridadsys.PS_CONSUMO W JOIN sgseguridadsys.PS_CONSUMO_NUTRICIONAL X ON W.ID_INSTITUCION = X.ID_INSTITUCION AND W.ID_CONSUMO = X.ID_CONSUMO JOIN sgseguridadsys.PS_ITEM Y ON X.ID_ITEM = Y.ID_ITEM JOIN UnidadesMast Z ON Y.ID_UNIDAD_MEDIDA = Z.UnidadCodigo WHERE Y.ID_CLASE = A.CodigoElemento AND X.ID_INSTITUCION = @INSTITUCION AND W.FECHA_INICIO BETWEEN @DESDE AND @HASTA AND W.FECHA_FIN BETWEEN @DESDE AND @HASTA),0) AS OTRO
	from 
	MA_MiscelaneosDetalle A 
	where CodigoTabla = 'ITEMCLASE') AS GENERAL

End  