--RES01 CABECERA sgseguridadsys.SNp_Res01Cabecera  
ALTER PROCEDURE sgseguridadsys.SNp_Res01Cabecera  
(  
 @PERIODO VARCHAR(6) ,--= '201802'  
 @PROGRAMA VARCHAR(3) --= 'AAM'  
)  
AS  
  
--DECLARE @PERIODO VARCHAR(6) = '201802'  
--DECLARE @PROGRAMA VARCHAR(3) = 'AAM'  
  
DECLARE @M_VALORACION VARCHAR(10)  
DECLARE @ID_INST_ACTUAL VARCHAR(10)  
DECLARE @NOM_INST_ACTUAL VARCHAR(100)  
  
DECLARE @GENERAL AS TABLE(  
 ID_INSTITUCION VARCHAR(10),  
 NOMBRE_INSTITUCION VARCHAR(100),  
 ID_VALOR VARCHAR(10),  
 NOMBRE_VALOR VARCHAR(100),  
 CANTIDAD INT,  
 PORCENTAJE DECIMAL(10,2)  
)  
  
DECLARE @INS_PROGRAMAS AS TABLE(  
 INSTITUCION VARCHAR(10),  
 PROGRAMA VARCHAR(3)  
)  
  
INSERT INTO @INS_PROGRAMAS VALUES   
('CANEV', 'AAM'),('CARID', 'AAM'),  
('CARID', 'NNA'),('DESAM', 'AAM'),  
('FRASI', 'NNA'), ('INMAC', 'NNA'),  
('PURIC', 'NNA'), ('SVPAU', 'AAM')  
  
IF @PROGRAMA = 'AAM'  
 SET @M_VALORACION = 'NUTRVALADU'  
ELSE  
 SET @M_VALORACION = 'NUTRVALNIN'  
  
DECLARE CURSOR_INTITUCION CURSOR FOR      
SELECT A.INSTITUCION, B.NOMBRE FROM @INS_PROGRAMAS A JOIN sgseguridadsys.PS_INSTITUCION B ON A.INSTITUCION = B.ID_INSTITUCION WHERE A.PROGRAMA = @PROGRAMA AND B.ESTADO = 'A'  
UNION ALL  
SELECT 'ALL', 'TOTAL'  
  
OPEN CURSOR_INTITUCION          
FETCH NEXT FROM CURSOR_INTITUCION INTO @ID_INST_ACTUAL, @NOM_INST_ACTUAL  
  
WHILE @@FETCH_STATUS = 0  
 BEGIN   
  
 DECLARE @TOTAL INT = (  
 select count(1) from   
 sgseguridadsys.PS_BENEFICIARIO Y  
 WHERE   
 (y.ID_INSTITUCION = @ID_INST_ACTUAL OR @ID_INST_ACTUAL = 'ALL') AND Y.ESTADO = 'ACT' AND Y.ID_PROGRAMA =@PROGRAMA)    
  
 INSERT INTO @GENERAL(ID_INSTITUCION, NOMBRE_INSTITUCION, ID_VALOR, NOMBRE_VALOR, CANTIDAD)  
  
 SELECT @ID_INST_ACTUAL, @NOM_INST_ACTUAL, 'ALL', 'Población total', @TOTAL  
  
 UNION ALL   
  
 SELECT @ID_INST_ACTUAL, @NOM_INST_ACTUAL, B.CodigoElemento, B.DescripcionLocal, (  
 select count(1) from   
 sgseguridadsys.PS_NUTRICION X JOIN    
 sgseguridadsys.PS_BENEFICIARIO Y ON Y.ID_INSTITUCION = X.ID_INSTITUCION AND Y.ID_BENEFICIARIO = X.ID_BENEFICIARIO AND Y.ID_PROGRAMA =@PROGRAMA and x.ID_PERIODO = @PERIODO  
 WHERE   
 (y.ID_INSTITUCION = @ID_INST_ACTUAL OR @ID_INST_ACTUAL = 'ALL') AND X.ID_ORIGEN = 'EVA' AND Y.ESTADO = 'ACT' AND ISNULL(X.EVALUADO, 'S') <> 'N' AND X.ID_VALORACION = B.CodigoElemento)   
 FROM MA_MiscelaneosDetalle B WHERE B.CodigoTabla = @M_VALORACION AND AplicacionCodigo = 'PS'  
   
 UNION ALL  
  
 SELECT @ID_INST_ACTUAL, @NOM_INST_ACTUAL, 'NE-PO', 'No Evaluados', (  
 select count(1) from   
 sgseguridadsys.PS_NUTRICION X JOIN    
 sgseguridadsys.PS_BENEFICIARIO Y ON Y.ID_INSTITUCION = X.ID_INSTITUCION AND Y.ID_BENEFICIARIO = X.ID_BENEFICIARIO AND Y.ID_PROGRAMA =@PROGRAMA and x.ID_PERIODO = @PERIODO  
 WHERE   
 (y.ID_INSTITUCION = @ID_INST_ACTUAL OR @ID_INST_ACTUAL = 'ALL') AND X.ID_ORIGEN = 'EVA' AND Y.ESTADO = 'ACT' AND ISNULL(X.EVALUADO, 'S') = 'N')   
  
 UPDATE @GENERAL SET PORCENTAJE = ROUND(CANTIDAD * 100.0 / @TOTAL, 2) WHERE ID_INSTITUCION = @ID_INST_ACTUAL AND @TOTAL <> 0  
  
 UPDATE @GENERAL SET PORCENTAJE = 0 WHERE ID_INSTITUCION = @ID_INST_ACTUAL AND @TOTAL = 0  
  
 FETCH NEXT FROM CURSOR_INTITUCION INTO @ID_INST_ACTUAL, @NOM_INST_ACTUAL  
 END    
          
CLOSE CURSOR_INTITUCION           
DEALLOCATE CURSOR_INTITUCION     
SELECT * FROM @GENERAL  
  
  
  