--RES04
ALTER PROCEDURE sgseguridadsys.SNp_Res04
(
	 @PERIODO VARCHAR(6)
)
AS
DECLARE @ID_INST_ACTUAL VARCHAR(10)
DECLARE @NOM_INST_ACTUAL VARCHAR(100)

DECLARE @GENERAL AS TABLE(
	ID_INSTITUCION VARCHAR(10),
	NOMBRE_INSTITUCION VARCHAR(100),
	ID_VALOR VARCHAR(10),
	NOMBRE_VALOR VARCHAR(100),
	PROMEDIO INT
)

DECLARE @INS_PROGRAMAS AS TABLE(
	INSTITUCION VARCHAR(10),
	PROGRAMA VARCHAR(3)
)

DECLARE CURSOR_INTITUCION CURSOR FOR    
SELECT B.ID_INSTITUCION, B.NOMBRE FROM sgseguridadsys.PS_INSTITUCION B WHERE B.ESTADO = 'A'

OPEN CURSOR_INTITUCION        
FETCH NEXT FROM CURSOR_INTITUCION INTO @ID_INST_ACTUAL, @NOM_INST_ACTUAL

WHILE @@FETCH_STATUS = 0
 BEGIN 

	INSERT INTO @GENERAL(ID_INSTITUCION, NOMBRE_INSTITUCION, ID_VALOR, NOMBRE_VALOR, PROMEDIO)
	SELECT @ID_INST_ACTUAL, @NOM_INST_ACTUAL, MM.CodigoElemento, MM.DescripcionLocal, (
	 SELECT ISNULL(AVG(GENE.PESO),0) FROM (
	 SELECT A.Sujeto, SUM(E.PESO) PESO FROM   
	 HR_EncuestaSujeto a join  
	 HR_EncuestaDetalle b on a.COMPANYOWNER = b.CompanyOwner and a.Secuencia = b.Secuencia and a.PERIODO = b.Periodo and a.Pregunta = b.Pregunta JOIN
	 HR_Encuesta d on d.CompanyOwner = a.COMPANYOWNER and d.Secuencia =a.Secuencia and d.Periodo = a.PERIODO
	 CROSS APPLY dbo.SplitString(CASE WHEN LEN(VALOR) = 1 THEN VALOR ELSE SUBSTRING(A.VALOR, 0, LEN(A.VALOR)) END, N',') AS C  
	 JOIN HR_EncuestaPreguntaValores E ON B.Pregunta = E.Pregunta AND E.Valor = C.Item  
	 JOIN HR_EncuestaPregunta F ON F.Pregunta = E.Pregunta
	 where d.TIPO = 'CLIMA' AND F.Area = MM.CodigoElemento AND A.PERIODO = @PERIODO and a.ID_INSTITUCION = @ID_INST_ACTUAL
	 GROUP BY A.Sujeto, A.Secuencia, A.PERIODO, A.COMPANYOWNER) AS GENE
	)
	FROM MA_MiscelaneosDetalle MM WHERE MM.CodigoTabla = 'AREASCLIMA' AND MM.AplicacionCodigo = 'HR'

	FETCH NEXT FROM CURSOR_INTITUCION INTO @ID_INST_ACTUAL, @NOM_INST_ACTUAL
 END  
        
CLOSE CURSOR_INTITUCION         
DEALLOCATE CURSOR_INTITUCION   

SELECT A.*, CAST(MAXIMOS.MAXIMO AS INT) FROM 
@GENERAL A JOIN 
(SELECT TABLA.Area, ISNULL(SUM(TABLA.MAXIMO),0) MAXIMO FROM (
SELECT 
G.AREA,
(SELECT MAX(H.PESO) FROM HR_EncuestaPreguntaValores H WHERE G.Pregunta = H.Pregunta)MAXIMO
FROM 
HR_EncuestaPregunta G
WHERE G.TipoEncuesta = 'CLIMA' ) AS TABLA
GROUP BY TABLA.Area) AS MAXIMOS ON A.ID_VALOR = MAXIMOS.Area
