USE [Spring_Canevaro_Cloud]
GO
/****** Object:  StoredProcedure [sgseguridadsys].[SNp_AS_ConsultarBeneficiario]    Script Date: 06/02/2019 09:11:50 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [sgseguridadsys].[SNp_AS_ConsultarBeneficiario]      
(      
@pNombreCompleto varchar(200),      
@pIdBenficiario INT,
@pDocumento varchar(20) ,    
@pInstitucion varchar(6),  
@pSexo varchar(1), 
@pPrograma varchar(3),  
@pEstado varchar(10), 
@pFechaNacimiento DATETIME     
 )   
 
 -- exec [sgseguridadsys].[SNp_AS_ConsultarBeneficiario] '',449,null,null,null,null,null,null   
AS 
DECLARE
@NOMBRE  AS VARCHAR(100)  ,
@PATERNO AS VARCHAR(100) ,
@MATERNO AS VARCHAR(100) ,
@NOMBRES AS VARCHAR(100) ,
@SEXO AS VARCHAR(100) ,
@FECHA_NACIMIENTO AS VARCHAR(100) ,
@EDAD AS VARCHAR(100) ,
@Pais AS VARCHAR(100) ,
@Departamento AS VARCHAR(100) ,
@Provincia AS VARCHAR(100) ,
@ZonaPostal AS VARCHAR(100) ,
@DOCUMENTO AS VARCHAR(100),
@ACTANACIMIENTO AS VARCHAR(100) ,
@NACIDOVIVO AS VARCHAR(100),
@BAUTIZO AS VARCHAR(100),
@VACUNACION AS VARCHAR(100),
@PELATOSCOPICO AS VARCHAR(100),
@CONSTANCIANOTAS AS VARCHAR(100),
@EPICRISIS AS VARCHAR(100),
@OTROSDOCUMENTOS AS VARCHAR(100),
@INRGESO AS VARCHAR(100),
@PERMANENCIA AS VARCHAR(100),
@VIOLENCIA AS VARCHAR(100),
@MALTRATOFISICO AS VARCHAR(100),
@MALTRATOPSICO AS VARCHAR(100),
@MALTRATOSEXUAL AS VARCHAR(100),
@DESPROTECCION AS VARCHAR(100),
@DESARROLLOINTEGRAL AS VARCHAR(100),
@AFECTACION AS VARCHAR(100),
@CENTROHOSP AS VARCHAR(100),
@VIAPUBLICA AS VARCHAR(100),
@OTROSCAUSALES AS VARCHAR(100),
@DERIVA AS VARCHAR(100),
@LEGAL AS VARCHAR(100),
@AREA AS VARCHAR(100),
@COMENTARIOS_INGRESO AS VARCHAR(1000),
@DepartamentoNombre AS VARCHAR(100),
@ProvinciaNombre AS VARCHAR(100),
@ZonaPostalNombre AS VARCHAR(100),
@DOMICILIO_DIRECCION AS VARCHAR(1000),
@DOMICILIO_REFERENCIA AS VARCHAR(1000),
@tenencia AS VARCHAR(500),
@material AS VARCHAR(500),
@agua AS VARCHAR(500),
@desague AS VARCHAR(500),
@electricidad AS VARCHAR(500),
@RADIO AS VARCHAR(500),
@TV AS VARCHAR(500),
@REFRIGERADORA AS VARCHAR(500),
@COCINA AS VARCHAR(500),
@INTERNET AS VARCHAR(500),
@OTROSEQUIPAMIENTOS AS VARCHAR(500),
@TELEFONO1 AS VARCHAR(100),
@PADRE_NOMBRE AS VARCHAR(100),
@PAPAVIVE AS VARCHAR(100),
@PADRE_NRO_DOCUMENTO AS VARCHAR(100),
@ocupacionpadre AS VARCHAR(100),
@MADRE_NOMBRE AS VARCHAR(100),
@MAMAVIVE AS VARCHAR(100),
@MADRE_NRO_DOCUMENTO AS VARCHAR(100),
@ocupacionmadre AS VARCHAR(100),
@APODERADO_NOMBRE AS VARCHAR(100),
@APODERADO_NRO_DOCUMENTO AS VARCHAR(100),
@APODERADO_ESPOSOA AS VARCHAR(100),
@INGRESO_MENSUAL AS VARCHAR(100),

@FECHA_INFORME_NUTRICION AS VARCHAR(100),
@ID_PERIODO_NUTRICION AS VARCHAR(100),
@PESO AS VARCHAR(100),
@TALLA AS VARCHAR(100),
@IMC AS VARCHAR(100),
@PESO_EDAD AS VARCHAR(100),
@TALLA_EDAD AS VARCHAR(100),
@PESO_TALLA AS VARCHAR(100),
@NOMBRE_SUPLEMENTO AS VARCHAR(100),
@NOMBRE_PERIMETRO AS VARCHAR(100),
@NOMBRE_PRESION AS VARCHAR(100),
@ID_VALORACION AS VARCHAR(100),
@ID_TIPO_DIETA AS VARCHAR(100),
@SUPLEMENTO_NUTRICIONAL_POR_DIA AS VARCHAR(100),
@TIPO_DIETA_POR_DIA AS VARCHAR(100),
@COMENTARIOS_NUTRICION AS VARCHAR(1000),
@VARIACION_PESO AS VARCHAR(100),
@ID_PERIODO_SOCIO AS VARCHAR(100),
@FECHA_INFORME_SOCIO AS VARCHAR(100),
@COMENTARIOS_SOCIO AS VARCHAR(1000),
@conflictos AS VARCHAR(100),
@COMUNICACION AS VARCHAR(100),
@emocional AS VARCHAR(100),
@cooperacion AS VARCHAR(100),
@asertividad AS VARCHAR(100),
@empatia AS VARCHAR(100),
@integracion AS VARCHAR(100),
@participacion AS VARCHAR(100),
@FECHA_INFORME_CAPACIDAD AS VARCHAR(100),
@NOMBRE_TIPO_INSTITUCION AS VARCHAR(100),
@NOMBRE_NIVEL AS VARCHAR(100),
@ID_GRADO_EDUCATIVO AS VARCHAR(100),
@ANIO_RETRASO AS VARCHAR(100),
@COMENTARIO_RETRASO AS VARCHAR(1000),
@ID_TIPO_COMUNICACION AS VARCHAR(100),
@COMENTARIO_RENDIMIENTO AS VARCHAR(1000),
@COMENTARIO_TALLERES AS VARCHAR(1000),
@ID_RIESGO_CAIDA AS VARCHAR(100),
@NOMBRE_HABILIDAD AS VARCHAR(100),
@ID_EVALUAR_OCUPACIONAL AS VARCHAR(100),
@COMENTARIO_CAPACIDAD AS VARCHAR(1000),
@ID_PERIODO_CAPACIDAD AS VARCHAR(100),
@GRADO_DEPENDENCIA_BARTHEL AS VARCHAR(100),
@GRADO_DEPENDENCIA_KATZ AS VARCHAR(100),
@PORCENTAJE_GRADO_BARTHEL AS VARCHAR(100),
@PORCENTAJE_GRADO_KATZ AS VARCHAR(100),
@ID_ILETRADO AS VARCHAR(100),
@ID_SAANEE AS VARCHAR(100),
@OCUPACION_ANTERIOR AS VARCHAR(100),
@ID_RIESGO_CAIDA_DETALLE AS VARCHAR(100),
@ID_PERIODO_SALUD AS VARCHAR(100),
@FECHA_INFORME_SALUD AS VARCHAR(100),
@HEMOGLOBINA AS VARCHAR(100),
@HEMOGLOBINA_RESULTADO AS VARCHAR(100),
@ID_TRATAMIENTO_ANEMIA AS VARCHAR(100),
@ID_DESCARTE_TBC AS VARCHAR(100),
@ID_DESCARTE_SEROLOGICO AS VARCHAR(100),
@ID_AYUDA_MEDICA AS VARCHAR(100),
@COMENTARIOS AS VARCHAR(1000),
@ID_TBC AS VARCHAR(100),
@ID_HTA AS VARCHAR(100),
@ID_DIABETES AS VARCHAR(100),
@ID_OSTEOARTROSIS AS VARCHAR(100),
@ID_COGNITIVO AS VARCHAR(100),
@ID_AFECTIVO AS VARCHAR(100),
@ID_GRUPOSANGUINEO AS VARCHAR(100),
@ID_FACTORERH AS VARCHAR(100),
@EDAD_MENARQUIA AS VARCHAR(100),
@FECHA_ULTIMA_MESTRUACION AS VARCHAR(100),
@Id_PRUEBA_VIH AS VARCHAR(100),
@OTRAS_ENFERMEDADES AS VARCHAR(100),
@ID_BENEFICIARIO INT,
@ID_INSTITUCION  AS VARCHAR(10),
@ID_COMPONENTE_CAPACIDAD INT,
@ID_COMPONENTE_SALUD INT,

@ID_NOMBRE varchar(150),
@ID_NOMBRE2 varchar(150),
@ID_NOMBRE3 varchar(150),
@ID_NOMBRE_AYUDA_BIOMECANICA varchar(150),
@ID_NOMBRE_AYUDA_BIOMECANICA2 varchar(150),
@ID_NOMBRE_AYUDA_BIOMECANICA3 varchar(150),
@ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA varchar(150),
@ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA2 varchar(150),
@ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA3 varchar(150),
@ID_NOMBRE_DIAGNOSTICO varchar(150),
@ID_NOMBRE_DIAGNOSTICO2 varchar(150),
@ID_NOMBRE_DIAGNOSTICO3 varchar(150),
@ID_NOMBRE_DISCAPACIDAD varchar(150),
@ID_NOMBRE_DISCAPACIDAD2 varchar(150),
@ID_NOMBRE_DISCAPACIDAD3 varchar(150),
@ID_NOMBRE_ESTADO varchar(150),
@ID_NOMBRE_ESTADO2 varchar(150),
@ID_NOMBRE_ESTADO3 varchar(150),
@ID_NOMBRE_EXAMEN varchar(150), 
@ID_NOMBRE_EXAMEN2 varchar(150),    
@ID_NOMBRE_EXAMEN3 varchar(150), 
@ID_NOMBRE_RESULTADO varchar(150),
@ID_NOMBRE_RESULTADO2 varchar(150),
@ID_NOMBRE_RESULTADO3 varchar(150),
@ID_NOMBRE_CONDICION varchar(150),
@ID_NOMBRE_CONDICION2 varchar(150),
@ID_NOMBRE_CONDICION3 varchar(150),
@ID_NOMBRE_SUB_CONDICION varchar(150),
@ID_NOMBRE_SUB_CONDICION2 varchar(150),
@ID_NOMBRE_SUB_CONDICION3 varchar(150),
@ID_NOMBRE_TERAPIA varchar(150), 
@ID_NOMBRE_TERAPIA2 varchar(150),      
@ID_NOMBRE_TERAPIA3 varchar(150),  
@ID_NOMBRE_TRATAMIENTO varchar(150),
@ID_NOMBRE_TRATAMIENTO2 varchar(150),
@ID_NOMBRE_TRATAMIENTO3 varchar(150)
     
BEGIN  

 IF OBJECT_ID('tempdb..##tmp_Beneficiario') IS NOT NULL            
      BEGIN            
        drop table ##tmp_Beneficiario            
      END

CREATE TABLE #tmp_PS_SALUD_AYUDA(
     [FILA] int NULL,
     [ID_AYUDA] VARCHAR(20),      
     [ID_NOMBRE] varchar(150)
)
CREATE TABLE #tmp_PS_SALUD_BIOMECANICA(
    [FILA] int NULL,
    [ID_TIPO_AYUDA] VARCHAR(20), 
	[ID_ESTADO_AYUDA] VARCHAR(20),      
    [ID_NOMBRE_AYUDA_BIOMECANICA] varchar(150),
	[ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA] varchar(150),
)
CREATE TABLE #tmp_PS_SALUD_DIAGNOSTICO(
 [FILA] int NULL,
 [ID_DIAGNSOTICO] VARCHAR(20),      
 [ID_NOMBRE_DIAGNOSTICO] varchar(150)
)
CREATE TABLE #tmp_PS_SALUD_DISCAPACIDAD(
 [FILA] int NULL,
 [ID_DISCAPACIDAD] VARCHAR(20),      
 [ID_NOMBRE_DISCAPACIDAD] varchar(150)
)
CREATE TABLE #tmp_PS_SALUD_ESTADO(
 [FILA] int NULL,
 [ID_ESTADO] VARCHAR(20),      
 [ID_NOMBRE_ESTADO] varchar(150)
)
CREATE TABLE #tmp_PS_SALUD_EXAMEN(
 [FILA] int NULL,
 [ID_EXAMEN] VARCHAR(20), 
 [ID_RESULTADO] VARCHAR(20),      
 [ID_NOMBRE_EXAMEN] varchar(150),    
 [ID_NOMBRE_RESULTADO] varchar(150)
)
CREATE TABLE #tmp_PS_SALUD_SUBCONDICION(
 [FILA] int NULL,
 [ID_CONDICION] VARCHAR(20),      
 [ID_NOMBRE_CONDICION] varchar(150),
 [ID_SUB_CONDICION] VARCHAR(20),      
 [ID_NOMBRE_SUB_CONDICION] varchar(150)
)
CREATE TABLE #tmp_PS_SALUD_TERAPIA(
 [FILA] int NULL,
 [ID_TERAPIA] VARCHAR(20),      
 [ID_NOMBRE_TERAPIA] varchar(150)
)
CREATE TABLE #tmp_PS_SALUD_TRATAMIENTO(
  [FILA] int NULL,
  [ID_TRATAMIENTO] VARCHAR(20),      
  [ID_NOMBRE_TRATAMIENTO] varchar(150)
)

create table ##tmp_Beneficiario (
 [NOMBRE] [varchar](100) COLLATE database_default  NULL ,  
 [PATERNO] [varchar](100) COLLATE database_default  NULL , 
 [MATERNO] [varchar](100) COLLATE database_default  NULL , 
 [NOMBRES] [varchar](300) COLLATE database_default  NULL , 
 [SEXO] [varchar](100) COLLATE database_default  NULL , 
 [FECHA_NACIMIENTO] [varchar](100) COLLATE database_default  NULL, 
 [EDAD] [varchar](100) COLLATE database_default  NULL , 
 [Pais] [varchar](100) COLLATE database_default  NULL , 
 [Departamento] [varchar](100) COLLATE database_default  NULL , 
 [Provincia] [varchar](100) COLLATE database_default  NULL , 
 [ZonaPostal] [varchar](100) COLLATE database_default  NULL , 
 [DOCUMENTO] [varchar](100) COLLATE database_default  NULL , 
 [ACTANACIMIENTO] [varchar](100) COLLATE database_default  NULL , 
 [NACIDOVIVO] [varchar](100) COLLATE database_default  NULL ,
 [BAUTIZO] [varchar](100) COLLATE database_default  NULL ,
 [VACUNACION] [varchar](100) COLLATE database_default  NULL ,
 [PELATOSCOPICO] [varchar](100) COLLATE database_default  NULL ,
 [CONSTANCIANOTAS] [varchar](100) COLLATE database_default  NULL ,
 [EPICRISIS] [varchar](100) COLLATE database_default  NULL ,
 [OTROSDOCUMENTOS] [varchar](100) COLLATE database_default  NULL ,
 INRGESO [varchar](100) COLLATE database_default  NULL ,
 PERMANENCIA [varchar](100) COLLATE database_default  NULL ,
 [VIOLENCIA] [varchar](100) COLLATE database_default  NULL ,
 [MALTRATOFISICO] [varchar](100) COLLATE database_default  NULL ,
 [MALTRATOPSICO] [varchar](100) COLLATE database_default  NULL ,
 [MALTRATOSEXUAL] [varchar](100) COLLATE database_default  NULL ,
 [DESPROTECCION] [varchar](100) COLLATE database_default  NULL ,
 [DESARROLLOINTEGRAL] [varchar](100) COLLATE database_default  NULL ,
 [AFECTACION] [varchar](100) COLLATE database_default  NULL ,
 [CENTROHOSP] [varchar](100) COLLATE database_default  NULL ,
 [VIAPUBLICA] [varchar](100) COLLATE database_default  NULL ,
 [OTROSCAUSALES] [varchar](100) COLLATE database_default  NULL ,
 [DERIVA] [varchar](100) COLLATE database_default  NULL ,
 [LEGAL] [varchar](100) COLLATE database_default  NULL ,
 [AREA] [varchar](100) COLLATE database_default  NULL ,
 [COMENTARIOS_INGRESO] [varchar](1000) COLLATE database_default  NULL ,
 
DepartamentoNombre [varchar](100) COLLATE database_default  NULL,
ProvinciaNombre [varchar](100) COLLATE database_default  NULL,
ZonaPostalNombre [varchar](100) COLLATE database_default  NULL,
DOMICILIO_DIRECCION [varchar](1000) COLLATE database_default  NULL,
DOMICILIO_REFERENCIA [varchar](1000) COLLATE database_default  NULL,
tenencia [varchar](500) COLLATE database_default  NULL,
material [varchar](500) COLLATE database_default  NULL,
agua [varchar](500) COLLATE database_default  NULL,
desague [varchar](500) COLLATE database_default  NULL,
electricidad [varchar](500) COLLATE database_default  NULL,
RADIO [varchar](500) COLLATE database_default  NULL,
TV [varchar](500) COLLATE database_default  NULL,
REFRIGERADORA [varchar](500) COLLATE database_default  NULL,
COCINA [varchar](500) COLLATE database_default  NULL,
INTERNET [varchar](500) COLLATE database_default  NULL,
OTROSEQUIPAMIENTOS [varchar](500) COLLATE database_default  NULL,
TELEFONO1 [varchar](100) COLLATE database_default  NULL,
PADRE_NOMBRE [varchar](100) COLLATE database_default  NULL,
PAPAVIVE [varchar](100) COLLATE database_default  NULL,
PADRE_NRO_DOCUMENTO [varchar](100) COLLATE database_default  NULL,
ocupacionpadre [varchar](100) COLLATE database_default  NULL,
MADRE_NOMBRE [varchar](100) COLLATE database_default  NULL,
MAMAVIVE [varchar](100) COLLATE database_default  NULL,
MADRE_NRO_DOCUMENTO [varchar](100) COLLATE database_default  NULL,
ocupacionmadre [varchar](100) COLLATE database_default  NULL,
APODERADO_NOMBRE [varchar](100) COLLATE database_default  NULL,
APODERADO_NRO_DOCUMENTO [varchar](100) COLLATE database_default  NULL,
APODERADO_ESPOSOA [varchar](100) COLLATE database_default  NULL,
INGRESO_MENSUAL [varchar](100) COLLATE database_default  NULL,
FECHA_INFORME_NUTRICION  [varchar](100) COLLATE database_default  NULL,
ID_PERIODO_NUTRICION  [varchar](100) COLLATE database_default  NULL,
PESO  [varchar](100) COLLATE database_default  NULL,
TALLA  [varchar](100) COLLATE database_default  NULL,
IMC  [varchar](100) COLLATE database_default  NULL,
PESO_EDAD  [varchar](100) COLLATE database_default  NULL,
TALLA_EDAD  [varchar](100) COLLATE database_default  NULL,
PESO_TALLA  [varchar](100) COLLATE database_default  NULL,
NOMBRE_SUPLEMENTO  [varchar](100) COLLATE database_default  NULL,
NOMBRE_PERIMETRO  [varchar](100) COLLATE database_default  NULL,
NOMBRE_PRESION  [varchar](100) COLLATE database_default  NULL,
ID_VALORACION  [varchar](100) COLLATE database_default  NULL,
ID_TIPO_DIETA  [varchar](100) COLLATE database_default  NULL,
SUPLEMENTO_NUTRICIONAL_POR_DIA  [varchar](100) COLLATE database_default  NULL,
TIPO_DIETA_POR_DIA  [varchar](100) COLLATE database_default  NULL,
COMENTARIOS_NUTRICION  [varchar](1000) COLLATE database_default  NULL,
VARIACION_PESO  [varchar](100) COLLATE database_default  NULL,
ID_PERIODO_SOCIO [varchar](100) COLLATE database_default  NULL,
FECHA_INFORME_SOCIO [varchar](100) COLLATE database_default  NULL,
COMENTARIOS_SOCIO [varchar](1000) COLLATE database_default  NULL,
conflictos [varchar](100) COLLATE database_default  NULL,
COMUNICACION [varchar](100) COLLATE database_default  NULL,
emocional [varchar](100) COLLATE database_default  NULL,
cooperacion [varchar](100) COLLATE database_default  NULL,
asertividad [varchar](100) COLLATE database_default  NULL,
empatia [varchar](100) COLLATE database_default  NULL,
integracion [varchar](100) COLLATE database_default  NULL,
participacion [varchar](100) COLLATE database_default  NULL,
FECHA_INFORME_CAPACIDAD [varchar](100) COLLATE database_default  NULL,
NOMBRE_TIPO_INSTITUCION [varchar](100) COLLATE database_default  NULL,
NOMBRE_NIVEL [varchar](100) COLLATE database_default  NULL,
ID_GRADO_EDUCATIVO [varchar](100) COLLATE database_default  NULL,
ANIO_RETRASO [varchar](100) COLLATE database_default  NULL,
COMENTARIO_RETRASO [varchar](1000) COLLATE database_default  NULL,
ID_TIPO_COMUNICACION [varchar](100) COLLATE database_default  NULL,
COMENTARIO_RENDIMIENTO [varchar](1000) COLLATE database_default  NULL,
COMENTARIO_TALLERES [varchar](1000) COLLATE database_default  NULL,
ID_RIESGO_CAIDA [varchar](100) COLLATE database_default  NULL,
NOMBRE_HABILIDAD [varchar](100) COLLATE database_default  NULL,
ID_EVALUAR_OCUPACIONAL [varchar](100) COLLATE database_default  NULL,
COMENTARIO_CAPACIDAD [varchar](1000) COLLATE database_default  NULL,
ID_PERIODO_CAPACIDAD [varchar](100) COLLATE database_default  NULL,
GRADO_DEPENDENCIA_BARTHEL [varchar](100) COLLATE database_default  NULL,
GRADO_DEPENDENCIA_KATZ [varchar](100) COLLATE database_default  NULL,
PORCENTAJE_GRADO_BARTHEL [varchar](100) COLLATE database_default  NULL,
PORCENTAJE_GRADO_KATZ [varchar](100) COLLATE database_default  NULL,
ID_ILETRADO [varchar](100) COLLATE database_default  NULL,
ID_SAANEE [varchar](100) COLLATE database_default  NULL,
OCUPACION_ANTERIOR [varchar](100) COLLATE database_default  NULL,
ID_RIESGO_CAIDA_DETALLE [varchar](100) COLLATE database_default  NULL,
ID_PERIODO_SALUD [varchar](100) COLLATE database_default  NULL,
FECHA_INFORME_SALUD [varchar](100) COLLATE database_default  NULL,
HEMOGLOBINA [varchar](100) COLLATE database_default  NULL,
HEMOGLOBINA_RESULTADO [varchar](100) COLLATE database_default  NULL,
ID_TRATAMIENTO_ANEMIA [varchar](100) COLLATE database_default  NULL,
ID_DESCARTE_TBC [varchar](100) COLLATE database_default  NULL,
ID_DESCARTE_SEROLOGICO [varchar](100) COLLATE database_default  NULL,
ID_AYUDA_MEDICA [varchar](100) COLLATE database_default  NULL,
COMENTARIOS [varchar](1000) COLLATE database_default  NULL,
ID_TBC [varchar](100) COLLATE database_default  NULL,
ID_HTA [varchar](100) COLLATE database_default  NULL,
ID_DIABETES [varchar](100) COLLATE database_default  NULL,
ID_OSTEOARTROSIS [varchar](100) COLLATE database_default  NULL,
ID_COGNITIVO [varchar](100) COLLATE database_default  NULL,
ID_AFECTIVO [varchar](100) COLLATE database_default  NULL,
ID_GRUPOSANGUINEO [varchar](100) COLLATE database_default  NULL,
ID_FACTORERH [varchar](100) COLLATE database_default  NULL,
EDAD_MENARQUIA [varchar](100) COLLATE database_default  NULL,
FECHA_ULTIMA_MESTRUACION [varchar](100) COLLATE database_default  NULL,
Id_PRUEBA_VIH [varchar](100) COLLATE database_default  NULL,
OTRAS_ENFERMEDADES [varchar](100) COLLATE database_default  NULL,
ID_BENEFICIARIO INT,
ID_INSTITUCION [varchar](10) COLLATE database_default  NULL,
ID_COMPONENTE_CAPACIDAD INT,
ID_COMPONENTE_SALUD INT,

[ID_NOMBRE] varchar(150),
[ID_NOMBRE2] varchar(150),
[ID_NOMBRE3] varchar(150),
[ID_NOMBRE_AYUDA_BIOMECANICA] varchar(150),
[ID_NOMBRE_AYUDA_BIOMECANICA2] varchar(150),
[ID_NOMBRE_AYUDA_BIOMECANICA3] varchar(150),
[ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA] varchar(150),
[ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA2] varchar(150),
[ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA3] varchar(150),
[ID_NOMBRE_DIAGNOSTICO] varchar(150),
[ID_NOMBRE_DIAGNOSTICO2] varchar(150),
[ID_NOMBRE_DIAGNOSTICO3] varchar(150),
[ID_NOMBRE_DISCAPACIDAD] varchar(150),
[ID_NOMBRE_DISCAPACIDAD2] varchar(150),
[ID_NOMBRE_DISCAPACIDAD3] varchar(150),
[ID_NOMBRE_ESTADO] varchar(150),
[ID_NOMBRE_ESTADO2] varchar(150),
[ID_NOMBRE_ESTADO3] varchar(150),
[ID_NOMBRE_EXAMEN] varchar(150), 
[ID_NOMBRE_EXAMEN2] varchar(150),  
[ID_NOMBRE_EXAMEN3] varchar(150),     
[ID_NOMBRE_RESULTADO] varchar(150),
[ID_NOMBRE_RESULTADO2] varchar(150),
[ID_NOMBRE_RESULTADO3] varchar(150),
[ID_NOMBRE_CONDICION] varchar(150),
[ID_NOMBRE_CONDICION2] varchar(150),
[ID_NOMBRE_CONDICION3] varchar(150),
[ID_NOMBRE_SUB_CONDICION] varchar(150),
[ID_NOMBRE_SUB_CONDICION2] varchar(150),
[ID_NOMBRE_SUB_CONDICION3] varchar(150),
[ID_NOMBRE_TERAPIA] varchar(150),  
[ID_NOMBRE_TERAPIA2] varchar(150),
[ID_NOMBRE_TERAPIA3] varchar(150),    
[ID_NOMBRE_TRATAMIENTO] varchar(150),
[ID_NOMBRE_TRATAMIENTO3] varchar(150),
[ID_NOMBRE_TRATAMIENTO2] varchar(150)
)


 INSERT INTO ##tmp_Beneficiario(
[NOMBRE],  
[PATERNO], 
[MATERNO], 
[NOMBRES], 
[SEXO], 
[FECHA_NACIMIENTO], 
[EDAD], 
[Pais], 
[Departamento], 
[Provincia], 
[ZonaPostal], 
[DOCUMENTO],
[ACTANACIMIENTO], 
[NACIDOVIVO],
[BAUTIZO],
[VACUNACION],
[PELATOSCOPICO],
[CONSTANCIANOTAS],
[EPICRISIS],
[OTROSDOCUMENTOS],
INRGESO,
PERMANENCIA,
[VIOLENCIA],
[MALTRATOFISICO],
[MALTRATOPSICO],
[MALTRATOSEXUAL],
[DESPROTECCION],
[DESARROLLOINTEGRAL],
[AFECTACION],
[CENTROHOSP],
[VIAPUBLICA],
[OTROSCAUSALES],
[DERIVA],
[LEGAL],
[AREA],
[COMENTARIOS_INGRESO],
DepartamentoNombre,
ProvinciaNombre,
ZonaPostalNombre,
DOMICILIO_DIRECCION,
DOMICILIO_REFERENCIA,
tenencia,
material,
agua,
desague,
electricidad,
RADIO,
TV,
REFRIGERADORA,
COCINA,
INTERNET,
OTROSEQUIPAMIENTOS,
TELEFONO1,
PADRE_NOMBRE,
PAPAVIVE,
PADRE_NRO_DOCUMENTO,
ocupacionpadre,
MADRE_NOMBRE,
MAMAVIVE,
MADRE_NRO_DOCUMENTO,
ocupacionmadre,
APODERADO_NOMBRE,
APODERADO_NRO_DOCUMENTO,
APODERADO_ESPOSOA,
INGRESO_MENSUAL,

FECHA_INFORME_NUTRICION,
ID_PERIODO_NUTRICION,
PESO,
TALLA,
IMC,
PESO_EDAD,
TALLA_EDAD,
PESO_TALLA,
NOMBRE_SUPLEMENTO,
NOMBRE_PERIMETRO,
NOMBRE_PRESION,
ID_VALORACION,
ID_TIPO_DIETA,
SUPLEMENTO_NUTRICIONAL_POR_DIA,
TIPO_DIETA_POR_DIA,
COMENTARIOS_NUTRICION,
VARIACION_PESO,
ID_PERIODO_SOCIO,
FECHA_INFORME_SOCIO,
COMENTARIOS_SOCIO,
conflictos,
COMUNICACION,
emocional,
cooperacion,
asertividad,
empatia,
integracion,
participacion,
FECHA_INFORME_CAPACIDAD,
NOMBRE_TIPO_INSTITUCION,
NOMBRE_NIVEL,
ID_GRADO_EDUCATIVO,
ANIO_RETRASO,
COMENTARIO_RETRASO,
ID_TIPO_COMUNICACION,
COMENTARIO_RENDIMIENTO,
COMENTARIO_TALLERES,
ID_RIESGO_CAIDA,
NOMBRE_HABILIDAD,
ID_EVALUAR_OCUPACIONAL,
COMENTARIO_CAPACIDAD,
ID_PERIODO_CAPACIDAD,
GRADO_DEPENDENCIA_BARTHEL,
GRADO_DEPENDENCIA_KATZ,
PORCENTAJE_GRADO_BARTHEL,
PORCENTAJE_GRADO_KATZ,
ID_ILETRADO,
ID_SAANEE,
OCUPACION_ANTERIOR,
ID_RIESGO_CAIDA_DETALLE,
ID_PERIODO_SALUD,
FECHA_INFORME_SALUD,
HEMOGLOBINA,
HEMOGLOBINA_RESULTADO,
ID_TRATAMIENTO_ANEMIA,
ID_DESCARTE_TBC,
ID_DESCARTE_SEROLOGICO,
ID_AYUDA_MEDICA,
COMENTARIOS,
ID_TBC,
ID_HTA,
ID_DIABETES,
ID_OSTEOARTROSIS,
ID_COGNITIVO,
ID_AFECTIVO,
ID_GRUPOSANGUINEO,
ID_FACTORERH,
EDAD_MENARQUIA,
FECHA_ULTIMA_MESTRUACION,
Id_PRUEBA_VIH,
OTRAS_ENFERMEDADES,
ID_BENEFICIARIO,
ID_INSTITUCION,
ID_COMPONENTE_CAPACIDAD,
ID_COMPONENTE_SALUD 

 )

 SELECT
isnull(U.NOMBRE, ''),
isnull(APELLIDO_PATERNO, ''),
isnull(APELLIDO_MATERNO, ''),
isnull(NOMBRES, ''),
isnull(CASE WHEN ID_SEXO = 'F' THEN 'Femenino' when ID_SEXO = 'M' then 'Masculino' else '' END, '') AS SEXO,
isnull(CONVERT(VARCHAR(10), FECHA_NACIMIENTO, 103), '') NACIMIENTO,
isnull(cast(EDAD as varchar(10)), ''),
isnull(C.DescripcionCorta, ''),
isnull(D.DescripcionCorta, ''),
isnull(E.DescripcionCorta, ''),
isnull(F.DescripcionCorta, ''),
isnull(B.DOCUMENTO, ''),

isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_DOCUMENTO aa where aa.ID_ENTIDAD = b.ID_ENTIDAD and aa.ID_TIPO_DOCUMENTO = 'AN'), '') ACTANACIMIENTO,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_DOCUMENTO aa where aa.ID_ENTIDAD = b.ID_ENTIDAD and aa.ID_TIPO_DOCUMENTO = 'CN'), '') NACIDOVIVO,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_DOCUMENTO aa where aa.ID_ENTIDAD = b.ID_ENTIDAD and aa.ID_TIPO_DOCUMENTO = 'PB'), '') BAUTIZO,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_DOCUMENTO aa where aa.ID_ENTIDAD = b.ID_ENTIDAD and aa.ID_TIPO_DOCUMENTO = 'TV'), '') VACUNACION,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_DOCUMENTO aa where aa.ID_ENTIDAD = b.ID_ENTIDAD and aa.ID_TIPO_DOCUMENTO = 'RP') , '')PELATOSCOPICO,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_DOCUMENTO aa where aa.ID_ENTIDAD = b.ID_ENTIDAD and aa.ID_TIPO_DOCUMENTO = 'CNO') , '')CONSTANCIANOTAS,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_DOCUMENTO aa where aa.ID_ENTIDAD = b.ID_ENTIDAD and aa.ID_TIPO_DOCUMENTO = 'EP') , '')EPICRISIS,
isnull(sgseguridadsys.Fn_ObtenerOtrosDocumentosNNA(b.ID_ENTIDAD) , '')OTROSDOCUMENTOS,
isnull(CONVERT(VARCHAR(10), G.FECHA_INGRESO, 103) , '')INRGESO,
isnull(cast(DATEDIFF(day, G.FECHA_INGRESO, GETDATE()) as varchar(100)) , '')PERMANENCIA,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'VFAM' ), '') VIOLENCIA,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'MFIS' ) , '')MALTRATOFISICO,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'MPSI' ) , '')MALTRATOPSICO,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'MSEX' ) , '')MALTRATOSEXUAL,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'DESFM') , '')DESPROTECCION,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'RDIN' ) , '')DESARROLLOINTEGRAL,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'TADR' ) , '')AFECTACION,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'ACEH' ) , '')CENTROHOSP,
isnull((select 'X' from sgseguridadsys.PS_BENEFICIARIO_INGRESO_CAUSAL BA where BA.ID_INSTITUCION = A.ID_INSTITUCION AND BA.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND BA.ID_INGRESO = A.ID_COMPONENTE_INGRESO AND ID_CAUSAL = 'AVIP' ) , '')VIAPUBLICA,
isnull(sgseguridadsys.Fn_ObtenerOtrosCausasNNA(b.ID_ENTIDAD, g.ID_INGRESO, a.ID_INSTITUCION), '') OTROSCAUSALES,
isnull(H.DescripcionLocal, '') DERIVA,
isnull(I.DescripcionLocal, '') LEGAL,
isnull(J.NOMBRE, '') AREA,
isnull(G.COMENTARIOS, '') COMENTARIOS_INGRESO,
isnull(K.DescripcionCorta, ''),
isnull(L.DescripcionCorta, ''),
isnull(M.DescripcionCorta, ''),
isnull(B.DOMICILIO_DIRECCION, ''),
isnull(B.DOMICILIO_REFERENCIA, ''),

isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('TENENCINNA',B.ID_TENENCIA), '')tenencia,
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('MATECONST',B.ID_MATERIAL_CONSTRUCCION), '')material,
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('SERAGUAPO',B.ID_SERVICIO_AGUA), '')agua,
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('SERDESAGU',B.ID_SERVICIO_DESAGUE), '')desague,
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('SERELECTR',B.ID_SERVICIO_ELECTRICIDAD), '')electricidad,

isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_EQUIPAMIENTO Ca where Ca.ID_ENTIDAD = b.ID_ENTIDAD and Ca.ID_EQUIPAMIENTO = 'RAD'), '') RADIO,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_EQUIPAMIENTO Ca where Ca.ID_ENTIDAD = b.ID_ENTIDAD and Ca.ID_EQUIPAMIENTO = 'TV') , '')TV,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_EQUIPAMIENTO Ca where Ca.ID_ENTIDAD = b.ID_ENTIDAD and Ca.ID_EQUIPAMIENTO = 'REF') , '')REFRIGERADORA,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_EQUIPAMIENTO Ca where Ca.ID_ENTIDAD = b.ID_ENTIDAD and Ca.ID_EQUIPAMIENTO = 'COC') , '')COCINA,
isnull((select 'X' from sgseguridadsys.PS_ENTIDAD_EQUIPAMIENTO Ca where Ca.ID_ENTIDAD = b.ID_ENTIDAD and Ca.ID_EQUIPAMIENTO = 'INTE') , '')INTERNET,
isnull(sgseguridadsys.Fn_ObtenerOtrosEquipamientosNNA(b.ID_ENTIDAD) , '')OTROSEQUIPAMIENTOS,
isnull(B.TELEFONO1, ''),
isnull(B.PADRE_NOMBRE, ''),
isnull(CASE WHEN B.PADRE_ID_VIVE = 'S' THEN 'Si' when b.PADRE_ID_VIVE = 'N' then 'No' else '' end, '') PAPAVIVE,
isnull(B.PADRE_NRO_DOCUMENTO, ''),
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('OCUPAFUN',B.PADRE_ID_OCUPACION), '')ocupacionpadre,
isnull(B.MADRE_NOMBRE, ''),
isnull(CASE WHEN B.MADRE_ID_VIVE = 'S' THEN 'Si' when b.MADRE_ID_VIVE = 'N' then 'No' else '' end, '') MAMAVIVE,
isnull(B.MADRE_NRO_DOCUMENTO, ''),
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('OCUPAFUN',B.MADRE_ID_OCUPACION), '')ocupacionmadre,
isnull(B.APODERADO_NOMBRE, ''),
isnull(B.APODERADO_NRO_DOCUMENTO, ''),
isnull(B.APODERADO_ESPOSOA, ''),
isnull(cast(B.INGRESO_MENSUAL as varchar(100)), ''),



isnull(CONVERT(VARCHAR(10), nutri.FECHA_INFORME, 103), '') FECHA_INFORME,
isnull(nutri.ID_PERIODO, ''),
isnull(cast(nutri.PESO as varchar(100)), ''),
isnull(cast(nutri.TALLA as varchar(100)), ''),
isnull(nutri.IMC,''),
isnull(nutri.PESO_EDAD,''),
isnull(nutri.TALLA_EDAD,''),
isnull(nutri.PESO_TALLA,''),
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('SUPLENUTRI',nutri.ID_SUPLEMENTO_NUTRICIONAL), '') NOMBRE_SUPLEMENTO,
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('PERIPIERNA',nutri.ID_PERIMETRO_PIERNA), '') NOMBRE_PERIMETRO,
isnull(sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('PRENMANU',nutri.ID_PRESION_MENSUAL), '') NOMBRE_PRESION,
isnull(nutri.ID_VALORACION, ''),
isnull(nutri.ID_TIPO_DIETA, ''), 
isnull(cast(nutri.SUPLEMENTO_NUTRICIONAL_POR_DIA  as varchar(100)),''),
isnull(cast(nutri.TIPO_DIETA_POR_DIA as varchar(100)),''),
isnull(nutri.COMENTARIOS,''),
isnull(cast(VARIACION_PESO as varchar(100)),''),

isnull(socioAmb.ID_PERIODO,''),
isnull(CONVERT(VARCHAR(10), socioAmb.FECHA_INFORME, 103), '') FECHA_INFORME,
isnull(socioAmb.COMENTARIOS,''),
isnull( sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_CONFLICTOS),'') as conflictos,
isnull(	sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_COMUNICACION),'') as COMUNICACION,
isnull(	sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_EMOCIONAL),'') as emocional,
isnull(	sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_COOPERACION),'') as cooperacion,
isnull(	sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_ASERTAVIDAD),'') as asertividad,
isnull(	sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_EMPATIA),'') as empatia,
isnull(	sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_INTEGRACION),'') as integracion,
isnull(	sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABISOCIAL',socioAmb.ID_PARTICIPACION),'') as participacion,

isnull(CONVERT(VARCHAR(10), capacidad.FECHA_INFORME, 103), '') FECHA_INFORME,
isnull( sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('TIPINSTCAP',capacidad.ID_TIPO_INSTITUCION),'') NOMBRE_TIPO_INSTITUCION,     
isnull( sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('NIVELCAPAC',capacidad.ID_NIVEL),'')NOMBRE_NIVEL,  
isnull( capacidad.ID_GRADO_EDUCATIVO,''),
isnull( capacidad.ANIO_RETRASO,''),
isnull( capacidad.COMENTARIO_RETRASO,''),
isnull( capacidad.ID_TIPO_COMUNICACION,''),
isnull( capacidad.COMENTARIO_RENDIMIENTO,''),
isnull( capacidad.COMENTARIO_TALLERES,''),
isnull( capacidad.ID_RIESGO_CAIDA,''),
isnull( sgseguridadsys.FN_OBTENER_NOMBRE_MISCELANEO('HABIOCUPA',capacidad.ID_HABILIDAD_OCUPACIONAL) ,'') NOMBRE_HABILIDAD,
isnull( capacidad.ID_EVALUAR_OCUPACIONAL,''),
isnull( capacidad.COMENTARIO_CAPACIDAD,''),
isnull( capacidad.ID_PERIODO,''),
isnull( capacidad.GRADO_DEPENDENCIA_BARTHEL,''),
isnull( capacidad.GRADO_DEPENDENCIA_KATZ,''),
isnull( cast(capacidad.PORCENTAJE_GRADO_BARTHEL as varchar(100)),''),
isnull( cast(capacidad.PORCENTAJE_GRADO_KATZ as varchar(100)),''),
isnull( capacidad.ID_ILETRADO,''),
isnull( capacidad.ID_SAANEE,''),
isnull( capacidad.OCUPACION_ANTERIOR,''),
isnull( capacidad.ID_RIESGO_CAIDA_DETALLE,''),

isnull( salud.ID_PERIODO,''),
isnull(CONVERT(VARCHAR(10), salud.FECHA_INFORME, 103), '') FECHA_INFORME,
isnull( cast(salud.HEMOGLOBINA as varchar(100)),''),
isnull( salud.HEMOGLOBINA_RESULTADO,''),
isnull( salud.ID_TRATAMIENTO_ANEMIA,''),
isnull( salud.ID_DESCARTE_TBC,''),
isnull( salud.ID_DESCARTE_SEROLOGICO,''),
isnull( salud.ID_AYUDA_MEDICA,''),
isnull( salud.COMENTARIOS,''),
isnull( salud.ID_TBC,''),
isnull( salud.ID_HTA,''),
isnull( salud.ID_DIABETES,''),
isnull( salud.ID_OSTEOARTROSIS,''),
isnull( salud.ID_COGNITIVO,''),
isnull( salud.ID_AFECTIVO,''),
isnull( salud.ID_GRUPOSANGUINEO,''),
isnull( salud.ID_FACTORERH,''),
isnull( salud.EDAD_MENARQUIA,''),
isnull(CONVERT(VARCHAR(10), salud.FECHA_ULTIMA_MESTRUACION, 103), '') FECHA_ULTIMA_MESTRUACION,
isnull( salud.Id_PRUEBA_VIH,''),
isnull( salud.OTRAS_ENFERMEDADES,''),

a.ID_BENEFICIARIO,
a.ID_INSTITUCION,
a.ID_COMPONENTE_CAPACIDAD,
a.ID_COMPONENTE_SALUD

FROM 
sgseguridadsys.PS_BENEFICIARIO a JOIN 
sgseguridadsys.PS_ENTIDAD b ON a.ID_BENEFICIARIO = b.ID_ENTIDAD LEFT JOIN
Pais C ON C.Pais = B.ID_NACIMIENTO_PAIS LEFT JOIN
Departamento D ON D.Pais = C.Pais AND D.Departamento = SUBSTRING(ISNULL(ID_NACIMIENTO_UBIGEO,''),1, 2)
LEFT JOIN
Provincia E ON E.Departamento = D.Departamento AND E.Provincia = SUBSTRING(ISNULL(ID_NACIMIENTO_UBIGEO,''),3, 2)
LEFT JOIN


ZonaPostal F ON F.Departamento = E.Departamento AND F.Provincia = E.Provincia AND F.CodigoPostal = SUBSTRING(ISNULL(ID_NACIMIENTO_UBIGEO,''),5, 2) LEFT JOIN
sgseguridadsys.PS_BENEFICIARIO_INGRESO G ON G.ID_INSTITUCION = A.ID_INSTITUCION AND G.ID_BENEFICIARIO = A.ID_BENEFICIARIO AND G.ID_INGRESO = A.ID_COMPONENTE_INGRESO LEFT JOIN
MA_MiscelaneosDetalle H ON H.CodigoTabla = 'INSDAAM' AND H.CodigoElemento = G.ID_INSTITUCION_DERIVA LEFT JOIN
MA_MiscelaneosDetalle I ON I.CodigoTabla = 'SITLEGNIN' AND I.CodigoElemento = G.ID_SITUACION_LEGAL LEFT JOIN
sgseguridadsys.PS_INSTITUCION_AREA J ON J.ID_INSTITUCION = A.ID_INSTITUCION AND J.ID_AREA = A.ID_AREA LEFT JOIN 
Departamento K ON K.Departamento = SUBSTRING(ISNULL(DOMICILIO_ID_UBIGEO,''),1, 2)LEFT JOIN
Provincia L ON L.Departamento = K.Departamento AND L.Provincia = SUBSTRING(ISNULL(DOMICILIO_ID_UBIGEO,''),3, 2)LEFT JOIN
ZonaPostal M ON M.Departamento = L.Departamento AND M.Provincia = L.Provincia AND M.CodigoPostal = SUBSTRING(ISNULL(DOMICILIO_ID_UBIGEO,''),5, 2) 

LEFT JOIN
sgseguridadsys.PS_INSTITUCION U ON U.ID_INSTITUCION = A.ID_INSTITUCION

LEFT JOIN sgseguridadsys.PS_NUTRICION nutri ON nutri.ID_BENEFICIARIO=a.ID_BENEFICIARIO 
and nutri.ID_INSTITUCION=a.ID_INSTITUCION
AND nutri.ID_NUTRICION=a.ID_COMPONENTE_NUTRICION

LEFT JOIN sgseguridadsys.PS_SOCIO_AMBIENTAL socioAmb ON socioAmb.ID_BENEFICIARIO=a.ID_BENEFICIARIO 
and socioAmb.ID_INSTITUCION=a.ID_INSTITUCION
AND socioAmb.ID_SOCIO_AMBIENTAL=a.ID_COMPONENTE_SOCIO_AMBIENTAL

LEFT JOIN sgseguridadsys.PS_CAPACIDAD capacidad ON capacidad.ID_BENEFICIARIO=a.ID_BENEFICIARIO 
and capacidad.ID_INSTITUCION=a.ID_INSTITUCION
AND capacidad.ID_CAPACIDAD=a.ID_COMPONENTE_CAPACIDAD

LEFT JOIN sgseguridadsys.PS_SALUD salud ON salud.ID_BENEFICIARIO=a.ID_BENEFICIARIO 
and salud.ID_INSTITUCION=a.ID_INSTITUCION
AND salud.ID_SALUD=a.ID_COMPONENTE_SALUD


WHERE 
a.ID_BENEFICIARIO = isnull(@pIdBenficiario, a.ID_BENEFICIARIO) 
and
b.NOMBRECOMPLETO like '%'+isnull(@pNombreCompleto, '')+'%' and
isnull(b.DOCUMENTO, 'doc') = isnull(@pDocumento, isnull(b.DOCUMENTO, 'doc')) and
a.ID_INSTITUCION = isnull(@pInstitucion, a.ID_INSTITUCION) and
isnull(b.ID_SEXO, 'sins') = isnull(@pSexo, isnull(b.ID_SEXO, 'sins')) and
b.FECHA_NACIMIENTO between isnull(@pFechaNacimiento, '1800-01-01') and isnull(@pFechaNacimiento, '2200-01-01') and
a.ID_PROGRAMA = isnull(@pPrograma, a.ID_PROGRAMA) and
a.ESTADO = isnull(@pEstado, a.ESTADO)


 DECLARE InsertBeneficiario CURSOR FOR   
  SELECT 
		[NOMBRE],  
		[PATERNO], 
		[MATERNO], 
		[NOMBRES], 
		[SEXO], 
		[FECHA_NACIMIENTO], 
		[EDAD], 
		[Pais], 
		[Departamento], 
		[Provincia], 
		[ZonaPostal], 
		[DOCUMENTO],
		[ACTANACIMIENTO], 
		[NACIDOVIVO],
		[BAUTIZO],
		[VACUNACION],
		[PELATOSCOPICO],
		[CONSTANCIANOTAS],
		[EPICRISIS],
		[OTROSDOCUMENTOS],
		INRGESO,
		PERMANENCIA,
		[VIOLENCIA],
		[MALTRATOFISICO],
		[MALTRATOPSICO],
		[MALTRATOSEXUAL],
		[DESPROTECCION],
		[DESARROLLOINTEGRAL],
		[AFECTACION],
		[CENTROHOSP],
		[VIAPUBLICA],
		[OTROSCAUSALES],
		[DERIVA],
		[LEGAL],
		[AREA],
		[COMENTARIOS_INGRESO],
		DepartamentoNombre,
		ProvinciaNombre,
		ZonaPostalNombre,
		DOMICILIO_DIRECCION,
		DOMICILIO_REFERENCIA,
		tenencia,
		material,
		agua,
		desague,
		electricidad,
		RADIO,
		TV,
		REFRIGERADORA,
		COCINA,
		INTERNET,
		OTROSEQUIPAMIENTOS,
		TELEFONO1,
		PADRE_NOMBRE,
		PAPAVIVE,
		PADRE_NRO_DOCUMENTO,
		ocupacionpadre,
		MADRE_NOMBRE,
		MAMAVIVE,
		MADRE_NRO_DOCUMENTO,
		ocupacionmadre,
		APODERADO_NOMBRE,
		APODERADO_NRO_DOCUMENTO,
		APODERADO_ESPOSOA,
		INGRESO_MENSUAL,

		FECHA_INFORME_NUTRICION,
		ID_PERIODO_NUTRICION,
		PESO,
		TALLA,
		IMC,
		PESO_EDAD,
		TALLA_EDAD,
		PESO_TALLA,
		NOMBRE_SUPLEMENTO,
		NOMBRE_PERIMETRO,
		NOMBRE_PRESION,
		ID_VALORACION,
		ID_TIPO_DIETA,
		SUPLEMENTO_NUTRICIONAL_POR_DIA,
		TIPO_DIETA_POR_DIA,
		COMENTARIOS_NUTRICION,
		VARIACION_PESO,
		ID_PERIODO_SOCIO,
		FECHA_INFORME_SOCIO,
		COMENTARIOS_SOCIO,
		conflictos,
		COMUNICACION,
		emocional,
		cooperacion,
		asertividad,
		empatia,
		integracion,
		participacion,
		FECHA_INFORME_CAPACIDAD,
		NOMBRE_TIPO_INSTITUCION,
		NOMBRE_NIVEL,
		ID_GRADO_EDUCATIVO,
		ANIO_RETRASO,
		COMENTARIO_RETRASO,
		ID_TIPO_COMUNICACION,
		COMENTARIO_RENDIMIENTO,
		COMENTARIO_TALLERES,
		ID_RIESGO_CAIDA,
		NOMBRE_HABILIDAD,
		ID_EVALUAR_OCUPACIONAL,
		COMENTARIO_CAPACIDAD,
		ID_PERIODO_CAPACIDAD,
		GRADO_DEPENDENCIA_BARTHEL,
		GRADO_DEPENDENCIA_KATZ,
		PORCENTAJE_GRADO_BARTHEL,
		PORCENTAJE_GRADO_KATZ,
		ID_ILETRADO,
		ID_SAANEE,
		OCUPACION_ANTERIOR,
		ID_RIESGO_CAIDA_DETALLE,
		ID_PERIODO_SALUD,
		FECHA_INFORME_SALUD,
		HEMOGLOBINA,
		HEMOGLOBINA_RESULTADO,
		ID_TRATAMIENTO_ANEMIA,
		ID_DESCARTE_TBC,
		ID_DESCARTE_SEROLOGICO,
		ID_AYUDA_MEDICA,
		COMENTARIOS,
		ID_TBC,
		ID_HTA,
		ID_DIABETES,
		ID_OSTEOARTROSIS,
		ID_COGNITIVO,
		ID_AFECTIVO,
		ID_GRUPOSANGUINEO,
		ID_FACTORERH,
		EDAD_MENARQUIA,
		FECHA_ULTIMA_MESTRUACION,
		Id_PRUEBA_VIH,
		OTRAS_ENFERMEDADES,
		ID_BENEFICIARIO,
		ID_INSTITUCION,
		ID_COMPONENTE_CAPACIDAD,
		ID_COMPONENTE_SALUD
  FROM ##tmp_Beneficiario

  OPEN InsertBeneficiario      
  FETCH InsertBeneficiario      
  INTO
		@NOMBRE   ,
		@PATERNO ,
		@MATERNO ,
		@NOMBRES ,
		@SEXO ,
		@FECHA_NACIMIENTO ,
		@EDAD ,
		@Pais ,
		@Departamento ,
		@Provincia ,
		@ZonaPostal ,
		@DOCUMENTO,
		@ACTANACIMIENTO ,
		@NACIDOVIVO,
		@BAUTIZO,
		@VACUNACION,
		@PELATOSCOPICO,
		@CONSTANCIANOTAS,
		@EPICRISIS,
		@OTROSDOCUMENTOS,
		@INRGESO,
		@PERMANENCIA,
		@VIOLENCIA,
		@MALTRATOFISICO,
		@MALTRATOPSICO,
		@MALTRATOSEXUAL,
		@DESPROTECCION,
		@DESARROLLOINTEGRAL,
		@AFECTACION,
		@CENTROHOSP,
		@VIAPUBLICA,
		@OTROSCAUSALES,
		@DERIVA,
		@LEGAL,
		@AREA,
		@COMENTARIOS_INGRESO,
		@DepartamentoNombre,
		@ProvinciaNombre,
		@ZonaPostalNombre,
		@DOMICILIO_DIRECCION,
		@DOMICILIO_REFERENCIA,
		@tenencia,
		@material,
		@agua,
		@desague,
		@electricidad,
		@RADIO,
		@TV,
		@REFRIGERADORA,
		@COCINA,
		@INTERNET,
		@OTROSEQUIPAMIENTOS,
		@TELEFONO1,
		@PADRE_NOMBRE,
		@PAPAVIVE,
		@PADRE_NRO_DOCUMENTO,
		@ocupacionpadre,
		@MADRE_NOMBRE,
		@MAMAVIVE,
		@MADRE_NRO_DOCUMENTO,
		@ocupacionmadre,
		@APODERADO_NOMBRE,
		@APODERADO_NRO_DOCUMENTO,
		@APODERADO_ESPOSOA,
		@INGRESO_MENSUAL,
        @FECHA_INFORME_NUTRICION,
		@ID_PERIODO_NUTRICION,
		@PESO,
		@TALLA,
		@IMC,
		@PESO_EDAD,
		@TALLA_EDAD,
		@PESO_TALLA,
		@NOMBRE_SUPLEMENTO,
		@NOMBRE_PERIMETRO,
		@NOMBRE_PRESION,
		@ID_VALORACION,
		@ID_TIPO_DIETA,
		@SUPLEMENTO_NUTRICIONAL_POR_DIA,
		@TIPO_DIETA_POR_DIA,
		@COMENTARIOS_NUTRICION,
		@VARIACION_PESO,
		@ID_PERIODO_SOCIO,
		@FECHA_INFORME_SOCIO,
		@COMENTARIOS_SOCIO,
		@conflictos,
		@COMUNICACION,
		@emocional,
		@cooperacion,
		@asertividad,
		@empatia,
		@integracion,
		@participacion,
		@FECHA_INFORME_CAPACIDAD,
		@NOMBRE_TIPO_INSTITUCION,
		@NOMBRE_NIVEL,
		@ID_GRADO_EDUCATIVO,
		@ANIO_RETRASO,
		@COMENTARIO_RETRASO,
		@ID_TIPO_COMUNICACION,
		@COMENTARIO_RENDIMIENTO,
		@COMENTARIO_TALLERES,
		@ID_RIESGO_CAIDA,
		@NOMBRE_HABILIDAD,
		@ID_EVALUAR_OCUPACIONAL,
		@COMENTARIO_CAPACIDAD,
		@ID_PERIODO_CAPACIDAD,
		@GRADO_DEPENDENCIA_BARTHEL,
		@GRADO_DEPENDENCIA_KATZ,
		@PORCENTAJE_GRADO_BARTHEL,
		@PORCENTAJE_GRADO_KATZ,
		@ID_ILETRADO,
		@ID_SAANEE,
		@OCUPACION_ANTERIOR,
		@ID_RIESGO_CAIDA_DETALLE,
		@ID_PERIODO_SALUD,
		@FECHA_INFORME_SALUD,
		@HEMOGLOBINA,
		@HEMOGLOBINA_RESULTADO,
		@ID_TRATAMIENTO_ANEMIA,
		@ID_DESCARTE_TBC,
		@ID_DESCARTE_SEROLOGICO,
		@ID_AYUDA_MEDICA,
		@COMENTARIOS,
		@ID_TBC,
		@ID_HTA,
		@ID_DIABETES,
		@ID_OSTEOARTROSIS,
		@ID_COGNITIVO,
		@ID_AFECTIVO,
		@ID_GRUPOSANGUINEO,
		@ID_FACTORERH,
		@EDAD_MENARQUIA,
		@FECHA_ULTIMA_MESTRUACION,
		@Id_PRUEBA_VIH,
		@OTRAS_ENFERMEDADES,
		@ID_BENEFICIARIO ,
		@ID_INSTITUCION ,
		@ID_COMPONENTE_CAPACIDAD,
		@ID_COMPONENTE_SALUD


 WHILE @@fetch_status = 0      
   BEGIN 

     IF OBJECT_ID('tempdb..#tmp_PS_SALUD_AYUDA') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_AYUDA      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_BIOMECANICA') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_BIOMECANICA      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_DIAGNOSTICO') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_DIAGNOSTICO      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_DISCAPACIDAD') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_DISCAPACIDAD      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_ESTADO') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_ESTADO      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_EXAMEN') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_EXAMEN      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_SUBCONDICION') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_SUBCONDICION      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_TERAPIA') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_TERAPIA      
      END

	  IF OBJECT_ID('tempdb..#tmp_PS_SALUD_TRATAMIENTO') IS NOT NULL      
      BEGIN      
        delete #tmp_PS_SALUD_TRATAMIENTO      
      END

	 -- INSERTAR AYUDA      
     INSERT INTO #tmp_PS_SALUD_AYUDA      
     (   [FILA],   
         [ID_AYUDA],      
         [ID_NOMBRE]    
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY ID_AYUDA ASC) AS sec,      
       ID_AYUDA,      
       detalle.DescripcionLocal      
     FROM sgseguridadsys.PS_SALUD_AYUDA  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='TIPAYUMEDI' AND detalle.CodigoElemento=ID_AYUDA
     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x INT      
               
     SET @x=1      
     SET @ID_NOMBRE=NULL  
	 SET @ID_NOMBRE2=NULL     
     SET @ID_NOMBRE3=NULL     
      
     while @x<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_AYUDA)      
     BEGIN      
        SELECT       
         @ID_NOMBRE=ID_NOMBRE      
        FROM #tmp_PS_SALUD_AYUDA WHERE FILA=1  
		
		SELECT       
         @ID_NOMBRE2=ID_NOMBRE      
        FROM #tmp_PS_SALUD_AYUDA WHERE FILA=2   

		SELECT       
         @ID_NOMBRE3=ID_NOMBRE      
        FROM #tmp_PS_SALUD_AYUDA WHERE FILA=3
      
      SET @x=@x+1      
     END      
 

  -- INSERTAR PS_SALUD_BIOMECANICA  
     INSERT INTO #tmp_PS_SALUD_BIOMECANICA      
     (   [FILA],   
         [ID_ESTADO_AYUDA],  
		 [ID_TIPO_AYUDA],    
         [ID_NOMBRE_AYUDA_BIOMECANICA],
		 [ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA]   
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY [ID_TIPO_AYUDA] ASC) AS sec,      
       ID_ESTADO_AYUDA, 
	   [ID_TIPO_AYUDA],      
       detalle.DescripcionLocal,
	   detalle1.DescripcionLocal    
     FROM sgseguridadsys.PS_SALUD_BIOMECANICA  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='TIPAYUBIO' AND detalle.CodigoElemento=ID_TIPO_AYUDA

	 JOIN MA_MiscelaneosDetalle detalle1 ON detalle1.AplicacionCodigo='PS'     
	 AND detalle1.CodigoTabla='ESTAPAYUBI' AND detalle1.CodigoElemento=ID_ESTADO_AYUDA

     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x1 INT      
               
     SET @x1=1      
     SET @ID_NOMBRE_AYUDA_BIOMECANICA=NULL  
	 SET @ID_NOMBRE_AYUDA_BIOMECANICA2=NULL 
	 SET @ID_NOMBRE_AYUDA_BIOMECANICA3=NULL 
	 SET @ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA=NULL  
	 SET @ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA2=NULL   
	 SET @ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA3=NULL   
         
      
     while @x1<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_BIOMECANICA)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_AYUDA_BIOMECANICA=ID_NOMBRE_AYUDA_BIOMECANICA , 
		 @ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA=ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA    
        FROM #tmp_PS_SALUD_BIOMECANICA WHERE FILA=1  
		
	   SELECT       
         @ID_NOMBRE_AYUDA_BIOMECANICA2=ID_NOMBRE_AYUDA_BIOMECANICA, 
		 @ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA2=ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA    
        FROM #tmp_PS_SALUD_BIOMECANICA WHERE FILA=2 

		 SELECT       
         @ID_NOMBRE_AYUDA_BIOMECANICA3=ID_NOMBRE_AYUDA_BIOMECANICA, 
		 @ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA3=ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA    
        FROM #tmp_PS_SALUD_BIOMECANICA WHERE FILA=3
      
      SET @x1=@x1+1      
     END 

	 -- INSERTAR PS_SALUD_DIAGNOSTICO      
    INSERT INTO #tmp_PS_SALUD_DIAGNOSTICO      
     (   [FILA],   
         [ID_DIAGNSOTICO],      
         [ID_NOMBRE_DIAGNOSTICO]    
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY ID_DIAGNOSTICO ASC) AS sec,      
       [ID_DIAGNOSTICO],      
       diag.Nombre      
     FROM sgseguridadsys.PS_SALUD_DIAGNOSTICO  
	 JOIN sgseguridadsys.SS_ge_diagnostico diag ON diag.IdDiagnostico=ID_DIAGNOSTICO
     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x2 INT      
               
     SET @x2=1      
     SET @ID_NOMBRE_DIAGNOSTICO=NULL  
	 SET @ID_NOMBRE_DIAGNOSTICO2=NULL     
	 SET @ID_NOMBRE_DIAGNOSTICO3=NULL  
         
      
     while @x2<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_DIAGNOSTICO)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_DIAGNOSTICO=ID_NOMBRE_DIAGNOSTICO      
        FROM #tmp_PS_SALUD_DIAGNOSTICO WHERE FILA=1  
		
		SELECT       
         @ID_NOMBRE_DIAGNOSTICO2=ID_NOMBRE_DIAGNOSTICO      
        FROM #tmp_PS_SALUD_DIAGNOSTICO WHERE FILA=2   

		SELECT       
         @ID_NOMBRE_DIAGNOSTICO3=ID_NOMBRE_DIAGNOSTICO      
        FROM #tmp_PS_SALUD_DIAGNOSTICO WHERE FILA=3
      
      SET @x2=@x2+1      
     END      
 
  -- INSERTAR PS_SALUD_DISCAPACIDAD   
     INSERT INTO #tmp_PS_SALUD_DISCAPACIDAD      
     (   [FILA],   
         [ID_DISCAPACIDAD],      
         [ID_NOMBRE_DISCAPACIDAD]    
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY [ID_DISCAPACIDAD] ASC) AS sec,      
       [ID_DISCAPACIDAD],      
       detalle.DescripcionLocal      
     FROM sgseguridadsys.PS_SALUD_DISCAPACIDAD  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='TIPDISCA' AND detalle.CodigoElemento=ID_DISCAPACIDAD
     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x3 INT      
               
     SET @x3=1      
     SET @ID_NOMBRE_DISCAPACIDAD=NULL  
	 SET @ID_NOMBRE_DISCAPACIDAD2=NULL 
	 SET @ID_NOMBRE_DISCAPACIDAD3=NULL     
             
     while @x3<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_DISCAPACIDAD)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_DISCAPACIDAD=ID_NOMBRE_DISCAPACIDAD      
        FROM #tmp_PS_SALUD_DISCAPACIDAD WHERE FILA=1  
		
		SELECT       
         @ID_NOMBRE_DISCAPACIDAD2=ID_NOMBRE_DISCAPACIDAD      
        FROM #tmp_PS_SALUD_DISCAPACIDAD WHERE FILA=2   

		SELECT       
         @ID_NOMBRE_DISCAPACIDAD3=ID_NOMBRE_DISCAPACIDAD      
        FROM #tmp_PS_SALUD_DISCAPACIDAD WHERE FILA=3 
      
      SET @x3=@x3+1      
     END 

	 -- INSERTAR PS_SALUD_ESTADO   
    INSERT INTO #tmp_PS_SALUD_ESTADO      
     (   [FILA],   
         [ID_ESTADO],      
         [ID_NOMBRE_ESTADO]    
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY [ID_ESTADO] ASC) AS sec,      
       [ID_ESTADO],      
       detalle.DescripcionLocal      
     FROM sgseguridadsys.PS_SALUD_ESTADO  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='ESTASALU' AND detalle.CodigoElemento=ID_ESTADO
     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x4 INT      
               
     SET @x4=1      
     SET @ID_NOMBRE_ESTADO=NULL  
	 SET @ID_NOMBRE_ESTADO2=NULL     
	 SET @ID_NOMBRE_ESTADO3=NULL  
             
     while @x4<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_ESTADO)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_ESTADO=ID_NOMBRE_ESTADO      
        FROM #tmp_PS_SALUD_ESTADO WHERE FILA=1  
		
		SELECT       
         @ID_NOMBRE_ESTADO2=ID_NOMBRE_ESTADO      
        FROM #tmp_PS_SALUD_ESTADO WHERE FILA=2  
		
		SELECT       
         @ID_NOMBRE_ESTADO3=ID_NOMBRE_ESTADO      
        FROM #tmp_PS_SALUD_ESTADO WHERE FILA=3    
      
      SET @x4=@x4+1      
     END 

     -- INSERTAR PS_SALUD_EXAMEN  
     INSERT INTO #tmp_PS_SALUD_EXAMEN      
     (   [FILA],   
         [ID_EXAMEN],  
		 [ID_RESULTADO],    
         [ID_NOMBRE_EXAMEN],
		 [ID_NOMBRE_RESULTADO]   
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY [ID_EXAMEN] ASC) AS sec,      
       [ID_EXAMEN], 
	   [ID_RESULTADO],      
       detalle.DescripcionLocal,
	   detalle1.DescripcionLocal    
     FROM sgseguridadsys.PS_SALUD_EXAMEN  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='EXAAUXI' AND detalle.CodigoElemento=[ID_EXAMEN]

	 JOIN MA_MiscelaneosDetalle detalle1 ON detalle1.AplicacionCodigo='PS'     
	 AND detalle1.CodigoTabla='EXARESU' AND detalle1.CodigoElemento=[ID_RESULTADO]

     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x5 INT      
               
     SET @x5=1      
     SET @ID_NOMBRE_EXAMEN=NULL  
	 SET @ID_NOMBRE_RESULTADO=NULL 
	 SET @ID_NOMBRE_EXAMEN2=NULL  
	 SET @ID_NOMBRE_RESULTADO2=NULL   
	 SET @ID_NOMBRE_EXAMEN3=NULL  
	 SET @ID_NOMBRE_RESULTADO3=NULL
         
      
     while @x5<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_EXAMEN)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_EXAMEN=ID_NOMBRE_EXAMEN , 
		 @ID_NOMBRE_RESULTADO=ID_NOMBRE_RESULTADO    
        FROM #tmp_PS_SALUD_EXAMEN WHERE FILA=1  
		
	   SELECT       
         @ID_NOMBRE_EXAMEN2=ID_NOMBRE_EXAMEN, 
		 @ID_NOMBRE_RESULTADO2=ID_NOMBRE_RESULTADO    
        FROM #tmp_PS_SALUD_EXAMEN WHERE FILA=2 

	   SELECT       
         @ID_NOMBRE_EXAMEN3=ID_NOMBRE_EXAMEN, 
		 @ID_NOMBRE_RESULTADO3=ID_NOMBRE_RESULTADO    
        FROM #tmp_PS_SALUD_EXAMEN WHERE FILA=3
      
      SET @x5=@x5+1      
     END 

   -- INSERTAR PS_SALUD_EXAMEN  
     INSERT INTO #tmp_PS_SALUD_SUBCONDICION      
     (   [FILA],   
         [ID_CONDICION],  
		 [ID_NOMBRE_CONDICION],    
         [ID_SUB_CONDICION],
		 [ID_NOMBRE_SUB_CONDICION]   
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY [ID_CONDICION] ASC) AS sec,      
       [ID_CONDICION], 
	   [ID_SUBCONDICION],      
       detalle.DescripcionLocal,
	   detalle1.DescripcionLocal    
     FROM sgseguridadsys.PS_SALUD_SUBCONDICION  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='EXAAUXI' AND detalle.CodigoElemento=[ID_CONDICION]

	 JOIN MA_MiscelaneosDetalle detalle1 ON detalle1.AplicacionCodigo='PS'     
	 AND detalle1.CodigoTabla='EXARESU' AND detalle1.CodigoElemento=[ID_SUBCONDICION]

     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x6 INT      
               
     SET @x6=1      
     SET @ID_NOMBRE_CONDICION=NULL  
	 SET @ID_NOMBRE_SUB_CONDICION=NULL 
	 SET @ID_NOMBRE_CONDICION2=NULL  
	 SET @ID_NOMBRE_SUB_CONDICION2=NULL   
	 SET @ID_NOMBRE_CONDICION3=NULL  
	 SET @ID_NOMBRE_SUB_CONDICION3=NULL  
         
      
     while @x6<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_SUBCONDICION)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_CONDICION=ID_NOMBRE_CONDICION , 
		 @ID_NOMBRE_SUB_CONDICION=ID_NOMBRE_SUB_CONDICION    
        FROM #tmp_PS_SALUD_SUBCONDICION WHERE FILA=1  
		
	   SELECT       
         @ID_NOMBRE_CONDICION2=ID_NOMBRE_CONDICION, 
		 @ID_NOMBRE_SUB_CONDICION2=ID_NOMBRE_SUB_CONDICION    
        FROM #tmp_PS_SALUD_SUBCONDICION WHERE FILA=2 

		SELECT       
         @ID_NOMBRE_CONDICION3=ID_NOMBRE_CONDICION, 
		 @ID_NOMBRE_SUB_CONDICION3=ID_NOMBRE_SUB_CONDICION    
        FROM #tmp_PS_SALUD_SUBCONDICION WHERE FILA=3
      
      SET @x6=@x6+1      
     END 


	  -- INSERTAR PS_SALUD_TERAPIA   
    INSERT INTO #tmp_PS_SALUD_TERAPIA      
     (   [FILA],   
         [ID_TERAPIA],      
         [ID_NOMBRE_TERAPIA]    
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY [ID_TERAPIA] ASC) AS sec,      
       [ID_TERAPIA],      
       detalle.DescripcionLocal      
     FROM sgseguridadsys.PS_SALUD_TERAPIA  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='TERAPIA' AND detalle.CodigoElemento=[ID_TERAPIA]
     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x7 INT      
               
     SET @x7=1      
     SET @ID_NOMBRE_TERAPIA=NULL  
	 SET @ID_NOMBRE_TERAPIA2=NULL
	 SET @ID_NOMBRE_TERAPIA3=NULL      
             
     while @x7<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_TERAPIA)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_TERAPIA=ID_NOMBRE_TERAPIA      
        FROM #tmp_PS_SALUD_TERAPIA WHERE FILA=1  
		
		SELECT       
         @ID_NOMBRE_TERAPIA2=ID_NOMBRE_TERAPIA      
        FROM #tmp_PS_SALUD_TERAPIA WHERE FILA=2  
		
		SELECT       
         @ID_NOMBRE_TERAPIA3=ID_NOMBRE_TERAPIA      
        FROM #tmp_PS_SALUD_TERAPIA WHERE FILA=3 
      
      SET @x7=@x7+1      
     END 

    -- INSERTAR PS_SALUD_TRATAMIENTO   
    INSERT INTO #tmp_PS_SALUD_TRATAMIENTO      
     (   [FILA],   
         [ID_TRATAMIENTO],      
         [ID_NOMBRE_TRATAMIENTO]    
     )      
     SELECT       
       ROW_NUMBER() OVER(ORDER BY [ID_TRATAMIENTO] ASC) AS sec,      
       [ID_TRATAMIENTO],      
       detalle.DescripcionLocal      
     FROM sgseguridadsys.PS_SALUD_TRATAMIENTO  
	 JOIN MA_MiscelaneosDetalle detalle ON detalle.AplicacionCodigo='PS'     
	 AND detalle.CodigoTabla='RASTRATA' AND detalle.CodigoElemento=[ID_TRATAMIENTO]
     WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_SALUD=@ID_COMPONENTE_SALUD      
                  
     DECLARE @x8 INT      
               
     SET @x8=1      
     SET @ID_NOMBRE_TRATAMIENTO=NULL  
	 SET @ID_NOMBRE_TRATAMIENTO2=NULL     
	 SET @ID_NOMBRE_TRATAMIENTO3=NULL   
             
     while @x8<=(SELECT COUNT(1) FROM #tmp_PS_SALUD_TRATAMIENTO)      
     BEGIN      
        SELECT       
         @ID_NOMBRE_TRATAMIENTO=ID_NOMBRE_TRATAMIENTO      
        FROM #tmp_PS_SALUD_TRATAMIENTO WHERE FILA=1  
		
		SELECT       
         @ID_NOMBRE_TRATAMIENTO2=ID_NOMBRE_TRATAMIENTO      
        FROM #tmp_PS_SALUD_TRATAMIENTO WHERE FILA=2  
		
	    SELECT       
         @ID_NOMBRE_TRATAMIENTO3=ID_NOMBRE_TRATAMIENTO      
        FROM #tmp_PS_SALUD_TRATAMIENTO WHERE FILA=3 
      
      SET @x8=@x8+1      
     END   

	 

	 UPDATE ##tmp_Beneficiario  SET 
	       ID_NOMBRE=@ID_NOMBRE,  
	       ID_NOMBRE2=@ID_NOMBRE2,
		   ID_NOMBRE3=@ID_NOMBRE3,
		   ID_NOMBRE_AYUDA_BIOMECANICA=@ID_NOMBRE_AYUDA_BIOMECANICA,  
		   ID_NOMBRE_AYUDA_BIOMECANICA2=@ID_NOMBRE_AYUDA_BIOMECANICA2, 
		   ID_NOMBRE_AYUDA_BIOMECANICA3=@ID_NOMBRE_AYUDA_BIOMECANICA3, 
		   ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA=@ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA,  
		   ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA2=@ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA2 ,
		   ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA3=@ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA3 ,
		   ID_NOMBRE_DIAGNOSTICO=@ID_NOMBRE_DIAGNOSTICO,  
	       ID_NOMBRE_DIAGNOSTICO2=@ID_NOMBRE_DIAGNOSTICO2,
		   ID_NOMBRE_DIAGNOSTICO3=@ID_NOMBRE_DIAGNOSTICO3,
		   ID_NOMBRE_DISCAPACIDAD= @ID_NOMBRE_DISCAPACIDAD,
	       ID_NOMBRE_DISCAPACIDAD2=@ID_NOMBRE_DISCAPACIDAD2,
		   ID_NOMBRE_DISCAPACIDAD3=@ID_NOMBRE_DISCAPACIDAD3,
	       ID_NOMBRE_ESTADO=  @ID_NOMBRE_ESTADO,
	       ID_NOMBRE_ESTADO2= @ID_NOMBRE_ESTADO2,
		   ID_NOMBRE_ESTADO3= @ID_NOMBRE_ESTADO3,
	       ID_NOMBRE_EXAMEN=  @ID_NOMBRE_EXAMEN,
	       ID_NOMBRE_RESULTADO= @ID_NOMBRE_RESULTADO,
	       ID_NOMBRE_EXAMEN2= @ID_NOMBRE_EXAMEN2,
	       ID_NOMBRE_RESULTADO2= @ID_NOMBRE_RESULTADO2,
		   ID_NOMBRE_EXAMEN3= @ID_NOMBRE_EXAMEN2,
	       ID_NOMBRE_RESULTADO3= @ID_NOMBRE_RESULTADO2,
	       ID_NOMBRE_CONDICION= @ID_NOMBRE_CONDICION, 
	       ID_NOMBRE_SUB_CONDICION= @ID_NOMBRE_SUB_CONDICION,
	       ID_NOMBRE_CONDICION2= @ID_NOMBRE_CONDICION2,
	       ID_NOMBRE_SUB_CONDICION2=@ID_NOMBRE_SUB_CONDICION2,
		   ID_NOMBRE_CONDICION3= @ID_NOMBRE_CONDICION3,
	       ID_NOMBRE_SUB_CONDICION3=@ID_NOMBRE_SUB_CONDICION3,
	       ID_NOMBRE_TERAPIA= @ID_NOMBRE_TERAPIA,
	       ID_NOMBRE_TERAPIA2=@ID_NOMBRE_TERAPIA2,
		   ID_NOMBRE_TERAPIA3=@ID_NOMBRE_TERAPIA3,
	       ID_NOMBRE_TRATAMIENTO= @ID_NOMBRE_TRATAMIENTO ,
	       ID_NOMBRE_TRATAMIENTO2= @ID_NOMBRE_TRATAMIENTO2,
		   ID_NOMBRE_TRATAMIENTO3= @ID_NOMBRE_TRATAMIENTO3   



	 WHERE ID_INSTITUCION=@ID_INSTITUCION AND ID_BENEFICIARIO= @ID_BENEFICIARIO      
     AND ID_COMPONENTE_SALUD=@ID_COMPONENTE_SALUD
        
    FETCH InsertBeneficiario      
    INTO       
       @NOMBRE   ,
		@PATERNO ,
		@MATERNO ,
		@NOMBRES ,
		@SEXO ,
		@FECHA_NACIMIENTO ,
		@EDAD ,
		@Pais ,
		@Departamento ,
		@Provincia ,
		@ZonaPostal ,
		@DOCUMENTO,
		@ACTANACIMIENTO ,
		@NACIDOVIVO,
		@BAUTIZO,
		@VACUNACION,
		@PELATOSCOPICO,
		@CONSTANCIANOTAS,
		@EPICRISIS,
		@OTROSDOCUMENTOS,
		@INRGESO,
		@PERMANENCIA,
		@VIOLENCIA,
		@MALTRATOFISICO,
		@MALTRATOPSICO,
		@MALTRATOSEXUAL,
		@DESPROTECCION,
		@DESARROLLOINTEGRAL,
		@AFECTACION,
		@CENTROHOSP,
		@VIAPUBLICA,
		@OTROSCAUSALES,
		@DERIVA,
		@LEGAL,
		@AREA,
		@COMENTARIOS_INGRESO,
		@DepartamentoNombre,
		@ProvinciaNombre,
		@ZonaPostalNombre,
		@DOMICILIO_DIRECCION,
		@DOMICILIO_REFERENCIA,
		@tenencia,
		@material,
		@agua,
		@desague,
		@electricidad,
		@RADIO,
		@TV,
		@REFRIGERADORA,
		@COCINA,
		@INTERNET,
		@OTROSEQUIPAMIENTOS,
		@TELEFONO1,
		@PADRE_NOMBRE,
		@PAPAVIVE,
		@PADRE_NRO_DOCUMENTO,
		@ocupacionpadre,
		@MADRE_NOMBRE,
		@MAMAVIVE,
		@MADRE_NRO_DOCUMENTO,
		@ocupacionmadre,
		@APODERADO_NOMBRE,
		@APODERADO_NRO_DOCUMENTO,
		@APODERADO_ESPOSOA,
		@INGRESO_MENSUAL,

		@FECHA_INFORME_NUTRICION,
		@ID_PERIODO_NUTRICION,
		@PESO,
		@TALLA,
		@IMC,
		@PESO_EDAD,
		@TALLA_EDAD,
		@PESO_TALLA,
		@NOMBRE_SUPLEMENTO,
		@NOMBRE_PERIMETRO,
		@NOMBRE_PRESION,
		@ID_VALORACION,
		@ID_TIPO_DIETA,
		@SUPLEMENTO_NUTRICIONAL_POR_DIA,
		@TIPO_DIETA_POR_DIA,
		@COMENTARIOS_NUTRICION,
		@VARIACION_PESO,
		@ID_PERIODO_SOCIO,
		@FECHA_INFORME_SOCIO,
		@COMENTARIOS_SOCIO,
		@conflictos,
		@COMUNICACION,
		@emocional,
		@cooperacion,
		@asertividad,
		@empatia,
		@integracion,
		@participacion,
		@FECHA_INFORME_CAPACIDAD,
		@NOMBRE_TIPO_INSTITUCION,
		@NOMBRE_NIVEL,
		@ID_GRADO_EDUCATIVO,
		@ANIO_RETRASO,
		@COMENTARIO_RETRASO,
		@ID_TIPO_COMUNICACION,
		@COMENTARIO_RENDIMIENTO,
		@COMENTARIO_TALLERES,
		@ID_RIESGO_CAIDA,
		@NOMBRE_HABILIDAD,
		@ID_EVALUAR_OCUPACIONAL,
		@COMENTARIO_CAPACIDAD,
		@ID_PERIODO_CAPACIDAD,
		@GRADO_DEPENDENCIA_BARTHEL,
		@GRADO_DEPENDENCIA_KATZ,
		@PORCENTAJE_GRADO_BARTHEL,
		@PORCENTAJE_GRADO_KATZ,
		@ID_ILETRADO,
		@ID_SAANEE,
		@OCUPACION_ANTERIOR,
		@ID_RIESGO_CAIDA_DETALLE,
		@ID_PERIODO_SALUD,
		@FECHA_INFORME_SALUD,
		@HEMOGLOBINA,
		@HEMOGLOBINA_RESULTADO,
		@ID_TRATAMIENTO_ANEMIA,
		@ID_DESCARTE_TBC,
		@ID_DESCARTE_SEROLOGICO,
		@ID_AYUDA_MEDICA,
		@COMENTARIOS,
		@ID_TBC,
		@ID_HTA,
		@ID_DIABETES,
		@ID_OSTEOARTROSIS,
		@ID_COGNITIVO,
		@ID_AFECTIVO,
		@ID_GRUPOSANGUINEO,
		@ID_FACTORERH,
		@EDAD_MENARQUIA,
		@FECHA_ULTIMA_MESTRUACION,
		@Id_PRUEBA_VIH,
		@OTRAS_ENFERMEDADES,
		@ID_BENEFICIARIO ,
		@ID_INSTITUCION ,
		@ID_COMPONENTE_CAPACIDAD,
        @ID_COMPONENTE_SALUD
      
 END      
 CLOSE InsertBeneficiario      
    DEALLOCATE InsertBeneficiario      
      
      
  
  SELECT 
    [NOMBRE],  
		[PATERNO], 
		[MATERNO], 
		[NOMBRES], 
		[SEXO], 
		[FECHA_NACIMIENTO], 
		[EDAD], 
		[Pais], 
		[Departamento], 
		[Provincia], 
		[ZonaPostal], 
		[DOCUMENTO],
		[ACTANACIMIENTO], 
		[NACIDOVIVO],
		[BAUTIZO],
		[VACUNACION],
		[PELATOSCOPICO],
		[CONSTANCIANOTAS],
		[EPICRISIS],
		[OTROSDOCUMENTOS],
		INRGESO,
		PERMANENCIA,
		[VIOLENCIA],
		[MALTRATOFISICO],
		[MALTRATOPSICO],
		[MALTRATOSEXUAL],
		[DESPROTECCION],
		[DESARROLLOINTEGRAL],
		[AFECTACION],
		[CENTROHOSP],
		[VIAPUBLICA],
		[OTROSCAUSALES],
		[DERIVA],
		[LEGAL],
		[AREA],
		[COMENTARIOS_INGRESO],
		DepartamentoNombre,
		ProvinciaNombre,
		ZonaPostalNombre,
		DOMICILIO_DIRECCION,
		DOMICILIO_REFERENCIA,
		tenencia,
		material,
		agua,
		desague,
		electricidad,
		RADIO,
		TV,
		REFRIGERADORA,
		COCINA,
		INTERNET,
		OTROSEQUIPAMIENTOS,
		TELEFONO1,
		PADRE_NOMBRE,
		PAPAVIVE,
		PADRE_NRO_DOCUMENTO,
		ocupacionpadre,
		MADRE_NOMBRE,
		MAMAVIVE,
		MADRE_NRO_DOCUMENTO,
		ocupacionmadre,
		APODERADO_NOMBRE,
		APODERADO_NRO_DOCUMENTO,
		APODERADO_ESPOSOA,
		INGRESO_MENSUAL,
        FECHA_INFORME_NUTRICION,
		ID_PERIODO_NUTRICION,
		PESO,
		TALLA,
		IMC,
		PESO_EDAD,
		TALLA_EDAD,
		PESO_TALLA,
		NOMBRE_SUPLEMENTO,
		NOMBRE_PERIMETRO,
		NOMBRE_PRESION,
		ID_VALORACION,
		ID_TIPO_DIETA,
		SUPLEMENTO_NUTRICIONAL_POR_DIA,
		TIPO_DIETA_POR_DIA,
		COMENTARIOS_NUTRICION,
		VARIACION_PESO,
		ID_PERIODO_SOCIO,
		FECHA_INFORME_SOCIO,
		COMENTARIOS_SOCIO,
		conflictos,
		COMUNICACION,
		emocional,
		cooperacion,
		asertividad,
		empatia,
		integracion,
		participacion,
		FECHA_INFORME_CAPACIDAD,
		NOMBRE_TIPO_INSTITUCION,
		NOMBRE_NIVEL,
		ID_GRADO_EDUCATIVO,
		ANIO_RETRASO,
		COMENTARIO_RETRASO,
		ID_TIPO_COMUNICACION,
		COMENTARIO_RENDIMIENTO,
		COMENTARIO_TALLERES,
		ID_RIESGO_CAIDA,
		NOMBRE_HABILIDAD,
		ID_EVALUAR_OCUPACIONAL,
		COMENTARIO_CAPACIDAD,
		ID_PERIODO_CAPACIDAD,
		GRADO_DEPENDENCIA_BARTHEL,
		GRADO_DEPENDENCIA_KATZ,
		PORCENTAJE_GRADO_BARTHEL,
		PORCENTAJE_GRADO_KATZ,
		ID_ILETRADO,
		ID_SAANEE,
		OCUPACION_ANTERIOR,
		ID_RIESGO_CAIDA_DETALLE,
		ID_PERIODO_SALUD,
		FECHA_INFORME_SALUD,
		HEMOGLOBINA,
		HEMOGLOBINA_RESULTADO,
		ID_TRATAMIENTO_ANEMIA,
		ID_DESCARTE_TBC,
		ID_DESCARTE_SEROLOGICO,
		ID_AYUDA_MEDICA,
		COMENTARIOS,
		ID_TBC,
		ID_HTA,
		ID_DIABETES,
		ID_OSTEOARTROSIS,
		ID_COGNITIVO,
		ID_AFECTIVO,
		ID_GRUPOSANGUINEO,
		ID_FACTORERH,
		EDAD_MENARQUIA,
		FECHA_ULTIMA_MESTRUACION,
		Id_PRUEBA_VIH,
		OTRAS_ENFERMEDADES,

		isnull(ID_NOMBRE,''),  
	       isnull(ID_NOMBRE2,''),  
		   isnull(ID_NOMBRE3,'') , 
		   isnull(ID_NOMBRE_AYUDA_BIOMECANICA,  ''),  
		   isnull(ID_NOMBRE_AYUDA_BIOMECANICA2, ''),  
		   isnull(ID_NOMBRE_AYUDA_BIOMECANICA3, ''),  
		   isnull(ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA, ''),   
		   isnull(ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA2 ,''),  
		   isnull(ID_NOMBRE_ESTADO_AYUDA_BIOMECANICA3 ,''),  
		   isnull(ID_NOMBRE_DIAGNOSTICO,''),    
	       isnull(ID_NOMBRE_DIAGNOSTICO2,''),  
		   isnull(ID_NOMBRE_DIAGNOSTICO3,''),  
		   isnull(ID_NOMBRE_DISCAPACIDAD,''),  
	       isnull(ID_NOMBRE_DISCAPACIDAD2,''),  
		   isnull(ID_NOMBRE_DISCAPACIDAD3,''), 
	       isnull(ID_NOMBRE_ESTADO,''),  
	       isnull(ID_NOMBRE_ESTADO2,''),  
		   isnull(ID_NOMBRE_ESTADO3,''),  
	       isnull(ID_NOMBRE_EXAMEN,''),  
	       isnull(ID_NOMBRE_RESULTADO,''),  
	       isnull(ID_NOMBRE_EXAMEN2,''),  
	       isnull(ID_NOMBRE_RESULTADO2,''),  
		   isnull(ID_NOMBRE_EXAMEN3,''),  
	       isnull(ID_NOMBRE_RESULTADO3,''),  
	       isnull(ID_NOMBRE_CONDICION, ''),  
	       isnull(ID_NOMBRE_SUB_CONDICION,''),  
	       isnull(ID_NOMBRE_CONDICION2,''),  
	       isnull(ID_NOMBRE_SUB_CONDICION2,''),  
		   isnull(ID_NOMBRE_CONDICION3,''),  
	       isnull(ID_NOMBRE_SUB_CONDICION3,''),  
	       isnull(ID_NOMBRE_TERAPIA,''),  
	       isnull(ID_NOMBRE_TERAPIA2,''),  
		   isnull(ID_NOMBRE_TERAPIA3,''),  
	       isnull(ID_NOMBRE_TRATAMIENTO ,''),  
	       isnull(ID_NOMBRE_TRATAMIENTO2,''),  
		   isnull(ID_NOMBRE_TRATAMIENTO3,'')  
		
  FROM ##tmp_Beneficiario

END






